/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.pg_catalog.tables.pojos;


import java.beans.ConstructorProperties;
import java.io.Serializable;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.Nullable;


@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JsonbPopulateRecordset implements Serializable {

    private static final long serialVersionUID = 1L;

    private Object jsonbPopulateRecordset;

    public JsonbPopulateRecordset() {}

    public JsonbPopulateRecordset(JsonbPopulateRecordset value) {
        this.jsonbPopulateRecordset = value.jsonbPopulateRecordset;
    }

    @ConstructorProperties({ "jsonbPopulateRecordset" })
    public JsonbPopulateRecordset(
        @Nullable Object jsonbPopulateRecordset
    ) {
        this.jsonbPopulateRecordset = jsonbPopulateRecordset;
    }

    @Deprecated
    @Nullable
    public Object getJsonbPopulateRecordset() {
        return this.jsonbPopulateRecordset;
    }

    @Deprecated
    public void setJsonbPopulateRecordset(@Nullable Object jsonbPopulateRecordset) {
        this.jsonbPopulateRecordset = jsonbPopulateRecordset;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final JsonbPopulateRecordset other = (JsonbPopulateRecordset) obj;
        if (this.jsonbPopulateRecordset == null) {
            if (other.jsonbPopulateRecordset != null)
                return false;
        }
        else if (!this.jsonbPopulateRecordset.equals(other.jsonbPopulateRecordset))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.jsonbPopulateRecordset == null) ? 0 : this.jsonbPopulateRecordset.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("JsonbPopulateRecordset (");

        sb.append(jsonbPopulateRecordset);

        sb.append(")");
        return sb.toString();
    }
}
