/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.pg_catalog.tables.pojos;


import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.time.OffsetDateTime;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.Nullable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PgCursors implements Serializable {

    private static final long serialVersionUID = 1L;

    private String name;
    private String statement;
    private Boolean isHoldable;
    private Boolean isBinary;
    private Boolean isScrollable;
    private OffsetDateTime creationTime;

    public PgCursors() {}

    public PgCursors(PgCursors value) {
        this.name = value.name;
        this.statement = value.statement;
        this.isHoldable = value.isHoldable;
        this.isBinary = value.isBinary;
        this.isScrollable = value.isScrollable;
        this.creationTime = value.creationTime;
    }

    @ConstructorProperties({ "name", "statement", "isHoldable", "isBinary", "isScrollable", "creationTime" })
    public PgCursors(
        @Nullable String name,
        @Nullable String statement,
        @Nullable Boolean isHoldable,
        @Nullable Boolean isBinary,
        @Nullable Boolean isScrollable,
        @Nullable OffsetDateTime creationTime
    ) {
        this.name = name;
        this.statement = statement;
        this.isHoldable = isHoldable;
        this.isBinary = isBinary;
        this.isScrollable = isScrollable;
        this.creationTime = creationTime;
    }

    /**
     * Getter for <code>pg_catalog.pg_cursors.name</code>.
     */
    @Nullable
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>pg_catalog.pg_cursors.name</code>.
     */
    public void setName(@Nullable String name) {
        this.name = name;
    }

    /**
     * Getter for <code>pg_catalog.pg_cursors.statement</code>.
     */
    @Nullable
    public String getStatement() {
        return this.statement;
    }

    /**
     * Setter for <code>pg_catalog.pg_cursors.statement</code>.
     */
    public void setStatement(@Nullable String statement) {
        this.statement = statement;
    }

    /**
     * Getter for <code>pg_catalog.pg_cursors.is_holdable</code>.
     */
    @Nullable
    public Boolean getIsHoldable() {
        return this.isHoldable;
    }

    /**
     * Setter for <code>pg_catalog.pg_cursors.is_holdable</code>.
     */
    public void setIsHoldable(@Nullable Boolean isHoldable) {
        this.isHoldable = isHoldable;
    }

    /**
     * Getter for <code>pg_catalog.pg_cursors.is_binary</code>.
     */
    @Nullable
    public Boolean getIsBinary() {
        return this.isBinary;
    }

    /**
     * Setter for <code>pg_catalog.pg_cursors.is_binary</code>.
     */
    public void setIsBinary(@Nullable Boolean isBinary) {
        this.isBinary = isBinary;
    }

    /**
     * Getter for <code>pg_catalog.pg_cursors.is_scrollable</code>.
     */
    @Nullable
    public Boolean getIsScrollable() {
        return this.isScrollable;
    }

    /**
     * Setter for <code>pg_catalog.pg_cursors.is_scrollable</code>.
     */
    public void setIsScrollable(@Nullable Boolean isScrollable) {
        this.isScrollable = isScrollable;
    }

    /**
     * Getter for <code>pg_catalog.pg_cursors.creation_time</code>.
     */
    @Nullable
    public OffsetDateTime getCreationTime() {
        return this.creationTime;
    }

    /**
     * Setter for <code>pg_catalog.pg_cursors.creation_time</code>.
     */
    public void setCreationTime(@Nullable OffsetDateTime creationTime) {
        this.creationTime = creationTime;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PgCursors other = (PgCursors) obj;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.statement == null) {
            if (other.statement != null)
                return false;
        }
        else if (!this.statement.equals(other.statement))
            return false;
        if (this.isHoldable == null) {
            if (other.isHoldable != null)
                return false;
        }
        else if (!this.isHoldable.equals(other.isHoldable))
            return false;
        if (this.isBinary == null) {
            if (other.isBinary != null)
                return false;
        }
        else if (!this.isBinary.equals(other.isBinary))
            return false;
        if (this.isScrollable == null) {
            if (other.isScrollable != null)
                return false;
        }
        else if (!this.isScrollable.equals(other.isScrollable))
            return false;
        if (this.creationTime == null) {
            if (other.creationTime != null)
                return false;
        }
        else if (!this.creationTime.equals(other.creationTime))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.statement == null) ? 0 : this.statement.hashCode());
        result = prime * result + ((this.isHoldable == null) ? 0 : this.isHoldable.hashCode());
        result = prime * result + ((this.isBinary == null) ? 0 : this.isBinary.hashCode());
        result = prime * result + ((this.isScrollable == null) ? 0 : this.isScrollable.hashCode());
        result = prime * result + ((this.creationTime == null) ? 0 : this.creationTime.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PgCursors (");

        sb.append(name);
        sb.append(", ").append(statement);
        sb.append(", ").append(isHoldable);
        sb.append(", ").append(isBinary);
        sb.append(", ").append(isScrollable);
        sb.append(", ").append(creationTime);

        sb.append(")");
        return sb.toString();
    }
}
