/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.pg_catalog.tables.pojos;


import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.util.Arrays;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.Nullable;


/**
 * The table <code>pg_catalog.pg_event_trigger_dropped_objects</code>.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PgEventTriggerDroppedObjects implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long classid;
    private Long objid;
    private Integer objsubid;
    private Boolean original;
    private Boolean normal;
    private Boolean isTemporary;
    private String objectType;
    private String schemaName;
    private String objectName;
    private String objectIdentity;
    private String[] addressNames;
    private String[] addressArgs;

    public PgEventTriggerDroppedObjects() {}

    public PgEventTriggerDroppedObjects(PgEventTriggerDroppedObjects value) {
        this.classid = value.classid;
        this.objid = value.objid;
        this.objsubid = value.objsubid;
        this.original = value.original;
        this.normal = value.normal;
        this.isTemporary = value.isTemporary;
        this.objectType = value.objectType;
        this.schemaName = value.schemaName;
        this.objectName = value.objectName;
        this.objectIdentity = value.objectIdentity;
        this.addressNames = value.addressNames;
        this.addressArgs = value.addressArgs;
    }

    @ConstructorProperties({ "classid", "objid", "objsubid", "original", "normal", "isTemporary", "objectType", "schemaName", "objectName", "objectIdentity", "addressNames", "addressArgs" })
    public PgEventTriggerDroppedObjects(
        @Nullable Long classid,
        @Nullable Long objid,
        @Nullable Integer objsubid,
        @Nullable Boolean original,
        @Nullable Boolean normal,
        @Nullable Boolean isTemporary,
        @Nullable String objectType,
        @Nullable String schemaName,
        @Nullable String objectName,
        @Nullable String objectIdentity,
        @Nullable String[] addressNames,
        @Nullable String[] addressArgs
    ) {
        this.classid = classid;
        this.objid = objid;
        this.objsubid = objsubid;
        this.original = original;
        this.normal = normal;
        this.isTemporary = isTemporary;
        this.objectType = objectType;
        this.schemaName = schemaName;
        this.objectName = objectName;
        this.objectIdentity = objectIdentity;
        this.addressNames = addressNames;
        this.addressArgs = addressArgs;
    }

    /**
     * Getter for
     * <code>pg_catalog.pg_event_trigger_dropped_objects.classid</code>.
     */
    @Nullable
    public Long getClassid() {
        return this.classid;
    }

    /**
     * Setter for
     * <code>pg_catalog.pg_event_trigger_dropped_objects.classid</code>.
     */
    public void setClassid(@Nullable Long classid) {
        this.classid = classid;
    }

    /**
     * Getter for
     * <code>pg_catalog.pg_event_trigger_dropped_objects.objid</code>.
     */
    @Nullable
    public Long getObjid() {
        return this.objid;
    }

    /**
     * Setter for
     * <code>pg_catalog.pg_event_trigger_dropped_objects.objid</code>.
     */
    public void setObjid(@Nullable Long objid) {
        this.objid = objid;
    }

    /**
     * Getter for
     * <code>pg_catalog.pg_event_trigger_dropped_objects.objsubid</code>.
     */
    @Nullable
    public Integer getObjsubid() {
        return this.objsubid;
    }

    /**
     * Setter for
     * <code>pg_catalog.pg_event_trigger_dropped_objects.objsubid</code>.
     */
    public void setObjsubid(@Nullable Integer objsubid) {
        this.objsubid = objsubid;
    }

    /**
     * Getter for
     * <code>pg_catalog.pg_event_trigger_dropped_objects.original</code>.
     */
    @Nullable
    public Boolean getOriginal() {
        return this.original;
    }

    /**
     * Setter for
     * <code>pg_catalog.pg_event_trigger_dropped_objects.original</code>.
     */
    public void setOriginal(@Nullable Boolean original) {
        this.original = original;
    }

    /**
     * Getter for
     * <code>pg_catalog.pg_event_trigger_dropped_objects.normal</code>.
     */
    @Nullable
    public Boolean getNormal() {
        return this.normal;
    }

    /**
     * Setter for
     * <code>pg_catalog.pg_event_trigger_dropped_objects.normal</code>.
     */
    public void setNormal(@Nullable Boolean normal) {
        this.normal = normal;
    }

    /**
     * Getter for
     * <code>pg_catalog.pg_event_trigger_dropped_objects.is_temporary</code>.
     */
    @Nullable
    public Boolean getIsTemporary() {
        return this.isTemporary;
    }

    /**
     * Setter for
     * <code>pg_catalog.pg_event_trigger_dropped_objects.is_temporary</code>.
     */
    public void setIsTemporary(@Nullable Boolean isTemporary) {
        this.isTemporary = isTemporary;
    }

    /**
     * Getter for
     * <code>pg_catalog.pg_event_trigger_dropped_objects.object_type</code>.
     */
    @Nullable
    public String getObjectType() {
        return this.objectType;
    }

    /**
     * Setter for
     * <code>pg_catalog.pg_event_trigger_dropped_objects.object_type</code>.
     */
    public void setObjectType(@Nullable String objectType) {
        this.objectType = objectType;
    }

    /**
     * Getter for
     * <code>pg_catalog.pg_event_trigger_dropped_objects.schema_name</code>.
     */
    @Nullable
    public String getSchemaName() {
        return this.schemaName;
    }

    /**
     * Setter for
     * <code>pg_catalog.pg_event_trigger_dropped_objects.schema_name</code>.
     */
    public void setSchemaName(@Nullable String schemaName) {
        this.schemaName = schemaName;
    }

    /**
     * Getter for
     * <code>pg_catalog.pg_event_trigger_dropped_objects.object_name</code>.
     */
    @Nullable
    public String getObjectName() {
        return this.objectName;
    }

    /**
     * Setter for
     * <code>pg_catalog.pg_event_trigger_dropped_objects.object_name</code>.
     */
    public void setObjectName(@Nullable String objectName) {
        this.objectName = objectName;
    }

    /**
     * Getter for
     * <code>pg_catalog.pg_event_trigger_dropped_objects.object_identity</code>.
     */
    @Nullable
    public String getObjectIdentity() {
        return this.objectIdentity;
    }

    /**
     * Setter for
     * <code>pg_catalog.pg_event_trigger_dropped_objects.object_identity</code>.
     */
    public void setObjectIdentity(@Nullable String objectIdentity) {
        this.objectIdentity = objectIdentity;
    }

    /**
     * Getter for
     * <code>pg_catalog.pg_event_trigger_dropped_objects.address_names</code>.
     */
    @Nullable
    public String[] getAddressNames() {
        return this.addressNames;
    }

    /**
     * Setter for
     * <code>pg_catalog.pg_event_trigger_dropped_objects.address_names</code>.
     */
    public void setAddressNames(@Nullable String[] addressNames) {
        this.addressNames = addressNames;
    }

    /**
     * Getter for
     * <code>pg_catalog.pg_event_trigger_dropped_objects.address_args</code>.
     */
    @Nullable
    public String[] getAddressArgs() {
        return this.addressArgs;
    }

    /**
     * Setter for
     * <code>pg_catalog.pg_event_trigger_dropped_objects.address_args</code>.
     */
    public void setAddressArgs(@Nullable String[] addressArgs) {
        this.addressArgs = addressArgs;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PgEventTriggerDroppedObjects other = (PgEventTriggerDroppedObjects) obj;
        if (this.classid == null) {
            if (other.classid != null)
                return false;
        }
        else if (!this.classid.equals(other.classid))
            return false;
        if (this.objid == null) {
            if (other.objid != null)
                return false;
        }
        else if (!this.objid.equals(other.objid))
            return false;
        if (this.objsubid == null) {
            if (other.objsubid != null)
                return false;
        }
        else if (!this.objsubid.equals(other.objsubid))
            return false;
        if (this.original == null) {
            if (other.original != null)
                return false;
        }
        else if (!this.original.equals(other.original))
            return false;
        if (this.normal == null) {
            if (other.normal != null)
                return false;
        }
        else if (!this.normal.equals(other.normal))
            return false;
        if (this.isTemporary == null) {
            if (other.isTemporary != null)
                return false;
        }
        else if (!this.isTemporary.equals(other.isTemporary))
            return false;
        if (this.objectType == null) {
            if (other.objectType != null)
                return false;
        }
        else if (!this.objectType.equals(other.objectType))
            return false;
        if (this.schemaName == null) {
            if (other.schemaName != null)
                return false;
        }
        else if (!this.schemaName.equals(other.schemaName))
            return false;
        if (this.objectName == null) {
            if (other.objectName != null)
                return false;
        }
        else if (!this.objectName.equals(other.objectName))
            return false;
        if (this.objectIdentity == null) {
            if (other.objectIdentity != null)
                return false;
        }
        else if (!this.objectIdentity.equals(other.objectIdentity))
            return false;
        if (this.addressNames == null) {
            if (other.addressNames != null)
                return false;
        }
        else if (!Arrays.deepEquals(this.addressNames, other.addressNames))
            return false;
        if (this.addressArgs == null) {
            if (other.addressArgs != null)
                return false;
        }
        else if (!Arrays.deepEquals(this.addressArgs, other.addressArgs))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.classid == null) ? 0 : this.classid.hashCode());
        result = prime * result + ((this.objid == null) ? 0 : this.objid.hashCode());
        result = prime * result + ((this.objsubid == null) ? 0 : this.objsubid.hashCode());
        result = prime * result + ((this.original == null) ? 0 : this.original.hashCode());
        result = prime * result + ((this.normal == null) ? 0 : this.normal.hashCode());
        result = prime * result + ((this.isTemporary == null) ? 0 : this.isTemporary.hashCode());
        result = prime * result + ((this.objectType == null) ? 0 : this.objectType.hashCode());
        result = prime * result + ((this.schemaName == null) ? 0 : this.schemaName.hashCode());
        result = prime * result + ((this.objectName == null) ? 0 : this.objectName.hashCode());
        result = prime * result + ((this.objectIdentity == null) ? 0 : this.objectIdentity.hashCode());
        result = prime * result + ((this.addressNames == null) ? 0 : Arrays.deepHashCode(this.addressNames));
        result = prime * result + ((this.addressArgs == null) ? 0 : Arrays.deepHashCode(this.addressArgs));
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PgEventTriggerDroppedObjects (");

        sb.append(classid);
        sb.append(", ").append(objid);
        sb.append(", ").append(objsubid);
        sb.append(", ").append(original);
        sb.append(", ").append(normal);
        sb.append(", ").append(isTemporary);
        sb.append(", ").append(objectType);
        sb.append(", ").append(schemaName);
        sb.append(", ").append(objectName);
        sb.append(", ").append(objectIdentity);
        sb.append(", ").append(Arrays.deepToString(addressNames));
        sb.append(", ").append(Arrays.deepToString(addressArgs));

        sb.append(")");
        return sb.toString();
    }
}
