/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.pg_catalog.tables.pojos;


import java.beans.ConstructorProperties;
import java.io.Serializable;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.Nullable;


/**
 * The table <code>pg_catalog.pg_stat_progress_basebackup</code>.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PgStatProgressBasebackup implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer pid;
    private String phase;
    private Long backupTotal;
    private Long backupStreamed;
    private Long tablespacesTotal;
    private Long tablespacesStreamed;

    public PgStatProgressBasebackup() {}

    public PgStatProgressBasebackup(PgStatProgressBasebackup value) {
        this.pid = value.pid;
        this.phase = value.phase;
        this.backupTotal = value.backupTotal;
        this.backupStreamed = value.backupStreamed;
        this.tablespacesTotal = value.tablespacesTotal;
        this.tablespacesStreamed = value.tablespacesStreamed;
    }

    @ConstructorProperties({ "pid", "phase", "backupTotal", "backupStreamed", "tablespacesTotal", "tablespacesStreamed" })
    public PgStatProgressBasebackup(
        @Nullable Integer pid,
        @Nullable String phase,
        @Nullable Long backupTotal,
        @Nullable Long backupStreamed,
        @Nullable Long tablespacesTotal,
        @Nullable Long tablespacesStreamed
    ) {
        this.pid = pid;
        this.phase = phase;
        this.backupTotal = backupTotal;
        this.backupStreamed = backupStreamed;
        this.tablespacesTotal = tablespacesTotal;
        this.tablespacesStreamed = tablespacesStreamed;
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_progress_basebackup.pid</code>.
     */
    @Nullable
    public Integer getPid() {
        return this.pid;
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_progress_basebackup.pid</code>.
     */
    public void setPid(@Nullable Integer pid) {
        this.pid = pid;
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_progress_basebackup.phase</code>.
     */
    @Nullable
    public String getPhase() {
        return this.phase;
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_progress_basebackup.phase</code>.
     */
    public void setPhase(@Nullable String phase) {
        this.phase = phase;
    }

    /**
     * Getter for
     * <code>pg_catalog.pg_stat_progress_basebackup.backup_total</code>.
     */
    @Nullable
    public Long getBackupTotal() {
        return this.backupTotal;
    }

    /**
     * Setter for
     * <code>pg_catalog.pg_stat_progress_basebackup.backup_total</code>.
     */
    public void setBackupTotal(@Nullable Long backupTotal) {
        this.backupTotal = backupTotal;
    }

    /**
     * Getter for
     * <code>pg_catalog.pg_stat_progress_basebackup.backup_streamed</code>.
     */
    @Nullable
    public Long getBackupStreamed() {
        return this.backupStreamed;
    }

    /**
     * Setter for
     * <code>pg_catalog.pg_stat_progress_basebackup.backup_streamed</code>.
     */
    public void setBackupStreamed(@Nullable Long backupStreamed) {
        this.backupStreamed = backupStreamed;
    }

    /**
     * Getter for
     * <code>pg_catalog.pg_stat_progress_basebackup.tablespaces_total</code>.
     */
    @Nullable
    public Long getTablespacesTotal() {
        return this.tablespacesTotal;
    }

    /**
     * Setter for
     * <code>pg_catalog.pg_stat_progress_basebackup.tablespaces_total</code>.
     */
    public void setTablespacesTotal(@Nullable Long tablespacesTotal) {
        this.tablespacesTotal = tablespacesTotal;
    }

    /**
     * Getter for
     * <code>pg_catalog.pg_stat_progress_basebackup.tablespaces_streamed</code>.
     */
    @Nullable
    public Long getTablespacesStreamed() {
        return this.tablespacesStreamed;
    }

    /**
     * Setter for
     * <code>pg_catalog.pg_stat_progress_basebackup.tablespaces_streamed</code>.
     */
    public void setTablespacesStreamed(@Nullable Long tablespacesStreamed) {
        this.tablespacesStreamed = tablespacesStreamed;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PgStatProgressBasebackup other = (PgStatProgressBasebackup) obj;
        if (this.pid == null) {
            if (other.pid != null)
                return false;
        }
        else if (!this.pid.equals(other.pid))
            return false;
        if (this.phase == null) {
            if (other.phase != null)
                return false;
        }
        else if (!this.phase.equals(other.phase))
            return false;
        if (this.backupTotal == null) {
            if (other.backupTotal != null)
                return false;
        }
        else if (!this.backupTotal.equals(other.backupTotal))
            return false;
        if (this.backupStreamed == null) {
            if (other.backupStreamed != null)
                return false;
        }
        else if (!this.backupStreamed.equals(other.backupStreamed))
            return false;
        if (this.tablespacesTotal == null) {
            if (other.tablespacesTotal != null)
                return false;
        }
        else if (!this.tablespacesTotal.equals(other.tablespacesTotal))
            return false;
        if (this.tablespacesStreamed == null) {
            if (other.tablespacesStreamed != null)
                return false;
        }
        else if (!this.tablespacesStreamed.equals(other.tablespacesStreamed))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.pid == null) ? 0 : this.pid.hashCode());
        result = prime * result + ((this.phase == null) ? 0 : this.phase.hashCode());
        result = prime * result + ((this.backupTotal == null) ? 0 : this.backupTotal.hashCode());
        result = prime * result + ((this.backupStreamed == null) ? 0 : this.backupStreamed.hashCode());
        result = prime * result + ((this.tablespacesTotal == null) ? 0 : this.tablespacesTotal.hashCode());
        result = prime * result + ((this.tablespacesStreamed == null) ? 0 : this.tablespacesStreamed.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PgStatProgressBasebackup (");

        sb.append(pid);
        sb.append(", ").append(phase);
        sb.append(", ").append(backupTotal);
        sb.append(", ").append(backupStreamed);
        sb.append(", ").append(tablespacesTotal);
        sb.append(", ").append(tablespacesStreamed);

        sb.append(")");
        return sb.toString();
    }
}
