/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.pg_catalog.tables.pojos;


import java.beans.ConstructorProperties;
import java.io.Serializable;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.Nullable;


@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PgStatGetBackendIdset implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer pgStatGetBackendIdset;

    public PgStatGetBackendIdset() {}

    public PgStatGetBackendIdset(PgStatGetBackendIdset value) {
        this.pgStatGetBackendIdset = value.pgStatGetBackendIdset;
    }

    @ConstructorProperties({ "pgStatGetBackendIdset" })
    public PgStatGetBackendIdset(
        @Nullable Integer pgStatGetBackendIdset
    ) {
        this.pgStatGetBackendIdset = pgStatGetBackendIdset;
    }

    @Nullable
    public Integer getPgStatGetBackendIdset() {
        return this.pgStatGetBackendIdset;
    }

    public void setPgStatGetBackendIdset(@Nullable Integer pgStatGetBackendIdset) {
        this.pgStatGetBackendIdset = pgStatGetBackendIdset;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PgStatGetBackendIdset other = (PgStatGetBackendIdset) obj;
        if (this.pgStatGetBackendIdset == null) {
            if (other.pgStatGetBackendIdset != null)
                return false;
        }
        else if (!this.pgStatGetBackendIdset.equals(other.pgStatGetBackendIdset))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.pgStatGetBackendIdset == null) ? 0 : this.pgStatGetBackendIdset.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PgStatGetBackendIdset (");

        sb.append(pgStatGetBackendIdset);

        sb.append(")");
        return sb.toString();
    }
}
