/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.information_schema.tables.pojos;


import java.beans.ConstructorProperties;
import java.io.Serializable;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.Nullable;


@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RoutineSequenceUsage implements Serializable {

    private static final long serialVersionUID = 1L;

    private String specificCatalog;
    private String specificSchema;
    private String specificName;
    private String routineCatalog;
    private String routineSchema;
    private String routineName;
    private String sequenceCatalog;
    private String sequenceSchema;
    private String sequenceName;

    public RoutineSequenceUsage() {}

    public RoutineSequenceUsage(RoutineSequenceUsage value) {
        this.specificCatalog = value.specificCatalog;
        this.specificSchema = value.specificSchema;
        this.specificName = value.specificName;
        this.routineCatalog = value.routineCatalog;
        this.routineSchema = value.routineSchema;
        this.routineName = value.routineName;
        this.sequenceCatalog = value.sequenceCatalog;
        this.sequenceSchema = value.sequenceSchema;
        this.sequenceName = value.sequenceName;
    }

    @ConstructorProperties({ "specificCatalog", "specificSchema", "specificName", "routineCatalog", "routineSchema", "routineName", "sequenceCatalog", "sequenceSchema", "sequenceName" })
    public RoutineSequenceUsage(
        @Nullable String specificCatalog,
        @Nullable String specificSchema,
        @Nullable String specificName,
        @Nullable String routineCatalog,
        @Nullable String routineSchema,
        @Nullable String routineName,
        @Nullable String sequenceCatalog,
        @Nullable String sequenceSchema,
        @Nullable String sequenceName
    ) {
        this.specificCatalog = specificCatalog;
        this.specificSchema = specificSchema;
        this.specificName = specificName;
        this.routineCatalog = routineCatalog;
        this.routineSchema = routineSchema;
        this.routineName = routineName;
        this.sequenceCatalog = sequenceCatalog;
        this.sequenceSchema = sequenceSchema;
        this.sequenceName = sequenceName;
    }

    @Nullable
    public String getSpecificCatalog() {
        return this.specificCatalog;
    }

    public void setSpecificCatalog(@Nullable String specificCatalog) {
        this.specificCatalog = specificCatalog;
    }

    @Nullable
    public String getSpecificSchema() {
        return this.specificSchema;
    }

    public void setSpecificSchema(@Nullable String specificSchema) {
        this.specificSchema = specificSchema;
    }

    @Nullable
    public String getSpecificName() {
        return this.specificName;
    }

    public void setSpecificName(@Nullable String specificName) {
        this.specificName = specificName;
    }

    @Nullable
    public String getRoutineCatalog() {
        return this.routineCatalog;
    }

    public void setRoutineCatalog(@Nullable String routineCatalog) {
        this.routineCatalog = routineCatalog;
    }

    @Nullable
    public String getRoutineSchema() {
        return this.routineSchema;
    }

    public void setRoutineSchema(@Nullable String routineSchema) {
        this.routineSchema = routineSchema;
    }

    @Nullable
    public String getRoutineName() {
        return this.routineName;
    }

    public void setRoutineName(@Nullable String routineName) {
        this.routineName = routineName;
    }

    @Nullable
    public String getSequenceCatalog() {
        return this.sequenceCatalog;
    }

    public void setSequenceCatalog(@Nullable String sequenceCatalog) {
        this.sequenceCatalog = sequenceCatalog;
    }

    @Nullable
    public String getSequenceSchema() {
        return this.sequenceSchema;
    }

    public void setSequenceSchema(@Nullable String sequenceSchema) {
        this.sequenceSchema = sequenceSchema;
    }

    @Nullable
    public String getSequenceName() {
        return this.sequenceName;
    }

    public void setSequenceName(@Nullable String sequenceName) {
        this.sequenceName = sequenceName;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final RoutineSequenceUsage other = (RoutineSequenceUsage) obj;
        if (this.specificCatalog == null) {
            if (other.specificCatalog != null)
                return false;
        }
        else if (!this.specificCatalog.equals(other.specificCatalog))
            return false;
        if (this.specificSchema == null) {
            if (other.specificSchema != null)
                return false;
        }
        else if (!this.specificSchema.equals(other.specificSchema))
            return false;
        if (this.specificName == null) {
            if (other.specificName != null)
                return false;
        }
        else if (!this.specificName.equals(other.specificName))
            return false;
        if (this.routineCatalog == null) {
            if (other.routineCatalog != null)
                return false;
        }
        else if (!this.routineCatalog.equals(other.routineCatalog))
            return false;
        if (this.routineSchema == null) {
            if (other.routineSchema != null)
                return false;
        }
        else if (!this.routineSchema.equals(other.routineSchema))
            return false;
        if (this.routineName == null) {
            if (other.routineName != null)
                return false;
        }
        else if (!this.routineName.equals(other.routineName))
            return false;
        if (this.sequenceCatalog == null) {
            if (other.sequenceCatalog != null)
                return false;
        }
        else if (!this.sequenceCatalog.equals(other.sequenceCatalog))
            return false;
        if (this.sequenceSchema == null) {
            if (other.sequenceSchema != null)
                return false;
        }
        else if (!this.sequenceSchema.equals(other.sequenceSchema))
            return false;
        if (this.sequenceName == null) {
            if (other.sequenceName != null)
                return false;
        }
        else if (!this.sequenceName.equals(other.sequenceName))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.specificCatalog == null) ? 0 : this.specificCatalog.hashCode());
        result = prime * result + ((this.specificSchema == null) ? 0 : this.specificSchema.hashCode());
        result = prime * result + ((this.specificName == null) ? 0 : this.specificName.hashCode());
        result = prime * result + ((this.routineCatalog == null) ? 0 : this.routineCatalog.hashCode());
        result = prime * result + ((this.routineSchema == null) ? 0 : this.routineSchema.hashCode());
        result = prime * result + ((this.routineName == null) ? 0 : this.routineName.hashCode());
        result = prime * result + ((this.sequenceCatalog == null) ? 0 : this.sequenceCatalog.hashCode());
        result = prime * result + ((this.sequenceSchema == null) ? 0 : this.sequenceSchema.hashCode());
        result = prime * result + ((this.sequenceName == null) ? 0 : this.sequenceName.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RoutineSequenceUsage (");

        sb.append(specificCatalog);
        sb.append(", ").append(specificSchema);
        sb.append(", ").append(specificName);
        sb.append(", ").append(routineCatalog);
        sb.append(", ").append(routineSchema);
        sb.append(", ").append(routineName);
        sb.append(", ").append(sequenceCatalog);
        sb.append(", ").append(sequenceSchema);
        sb.append(", ").append(sequenceName);

        sb.append(")");
        return sb.toString();
    }
}
