/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.information_schema.tables.records;


import edu.java.domain.jooq.information_schema.tables._PgForeignServers;

import java.beans.ConstructorProperties;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class _PgForeignServersRecord extends TableRecordImpl<_PgForeignServersRecord> implements Record9<Long, String[], String, String, String, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>information_schema._pg_foreign_servers.oid</code>.
     */
    public void setOid(@Nullable Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>information_schema._pg_foreign_servers.oid</code>.
     */
    @Nullable
    public Long getOid() {
        return (Long) get(0);
    }

    /**
     * Setter for
     * <code>information_schema._pg_foreign_servers.srvoptions</code>.
     */
    public void setSrvoptions(@Nullable String[] value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>information_schema._pg_foreign_servers.srvoptions</code>.
     */
    @Nullable
    public String[] getSrvoptions() {
        return (String[]) get(1);
    }

    /**
     * Setter for
     * <code>information_schema._pg_foreign_servers.foreign_server_catalog</code>.
     */
    public void setForeignServerCatalog(@Nullable String value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>information_schema._pg_foreign_servers.foreign_server_catalog</code>.
     */
    @Nullable
    public String getForeignServerCatalog() {
        return (String) get(2);
    }

    /**
     * Setter for
     * <code>information_schema._pg_foreign_servers.foreign_server_name</code>.
     */
    public void setForeignServerName(@Nullable String value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>information_schema._pg_foreign_servers.foreign_server_name</code>.
     */
    @Nullable
    public String getForeignServerName() {
        return (String) get(3);
    }

    /**
     * Setter for
     * <code>information_schema._pg_foreign_servers.foreign_data_wrapper_catalog</code>.
     */
    public void setForeignDataWrapperCatalog(@Nullable String value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>information_schema._pg_foreign_servers.foreign_data_wrapper_catalog</code>.
     */
    @Nullable
    public String getForeignDataWrapperCatalog() {
        return (String) get(4);
    }

    /**
     * Setter for
     * <code>information_schema._pg_foreign_servers.foreign_data_wrapper_name</code>.
     */
    public void setForeignDataWrapperName(@Nullable String value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>information_schema._pg_foreign_servers.foreign_data_wrapper_name</code>.
     */
    @Nullable
    public String getForeignDataWrapperName() {
        return (String) get(5);
    }

    /**
     * Setter for
     * <code>information_schema._pg_foreign_servers.foreign_server_type</code>.
     */
    public void setForeignServerType(@Nullable String value) {
        set(6, value);
    }

    /**
     * Getter for
     * <code>information_schema._pg_foreign_servers.foreign_server_type</code>.
     */
    @Nullable
    public String getForeignServerType() {
        return (String) get(6);
    }

    /**
     * Setter for
     * <code>information_schema._pg_foreign_servers.foreign_server_version</code>.
     */
    public void setForeignServerVersion(@Nullable String value) {
        set(7, value);
    }

    /**
     * Getter for
     * <code>information_schema._pg_foreign_servers.foreign_server_version</code>.
     */
    @Nullable
    public String getForeignServerVersion() {
        return (String) get(7);
    }

    /**
     * Setter for
     * <code>information_schema._pg_foreign_servers.authorization_identifier</code>.
     */
    public void setAuthorizationIdentifier(@Nullable String value) {
        set(8, value);
    }

    /**
     * Getter for
     * <code>information_schema._pg_foreign_servers.authorization_identifier</code>.
     */
    @Nullable
    public String getAuthorizationIdentifier() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row9<Long, String[], String, String, String, String, String, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row9<Long, String[], String, String, String, String, String, String, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return _PgForeignServers._PG_FOREIGN_SERVERS.OID;
    }

    @Override
    @NotNull
    public Field<String[]> field2() {
        return _PgForeignServers._PG_FOREIGN_SERVERS.SRVOPTIONS;
    }

    @Override
    @NotNull
    public Field<String> field3() {
        return _PgForeignServers._PG_FOREIGN_SERVERS.FOREIGN_SERVER_CATALOG;
    }

    @Override
    @NotNull
    public Field<String> field4() {
        return _PgForeignServers._PG_FOREIGN_SERVERS.FOREIGN_SERVER_NAME;
    }

    @Override
    @NotNull
    public Field<String> field5() {
        return _PgForeignServers._PG_FOREIGN_SERVERS.FOREIGN_DATA_WRAPPER_CATALOG;
    }

    @Override
    @NotNull
    public Field<String> field6() {
        return _PgForeignServers._PG_FOREIGN_SERVERS.FOREIGN_DATA_WRAPPER_NAME;
    }

    @Override
    @NotNull
    public Field<String> field7() {
        return _PgForeignServers._PG_FOREIGN_SERVERS.FOREIGN_SERVER_TYPE;
    }

    @Override
    @NotNull
    public Field<String> field8() {
        return _PgForeignServers._PG_FOREIGN_SERVERS.FOREIGN_SERVER_VERSION;
    }

    @Override
    @NotNull
    public Field<String> field9() {
        return _PgForeignServers._PG_FOREIGN_SERVERS.AUTHORIZATION_IDENTIFIER;
    }

    @Override
    @Nullable
    public Long component1() {
        return getOid();
    }

    @Override
    @Nullable
    public String[] component2() {
        return getSrvoptions();
    }

    @Override
    @Nullable
    public String component3() {
        return getForeignServerCatalog();
    }

    @Override
    @Nullable
    public String component4() {
        return getForeignServerName();
    }

    @Override
    @Nullable
    public String component5() {
        return getForeignDataWrapperCatalog();
    }

    @Override
    @Nullable
    public String component6() {
        return getForeignDataWrapperName();
    }

    @Override
    @Nullable
    public String component7() {
        return getForeignServerType();
    }

    @Override
    @Nullable
    public String component8() {
        return getForeignServerVersion();
    }

    @Override
    @Nullable
    public String component9() {
        return getAuthorizationIdentifier();
    }

    @Override
    @Nullable
    public Long value1() {
        return getOid();
    }

    @Override
    @Nullable
    public String[] value2() {
        return getSrvoptions();
    }

    @Override
    @Nullable
    public String value3() {
        return getForeignServerCatalog();
    }

    @Override
    @Nullable
    public String value4() {
        return getForeignServerName();
    }

    @Override
    @Nullable
    public String value5() {
        return getForeignDataWrapperCatalog();
    }

    @Override
    @Nullable
    public String value6() {
        return getForeignDataWrapperName();
    }

    @Override
    @Nullable
    public String value7() {
        return getForeignServerType();
    }

    @Override
    @Nullable
    public String value8() {
        return getForeignServerVersion();
    }

    @Override
    @Nullable
    public String value9() {
        return getAuthorizationIdentifier();
    }

    @Override
    @NotNull
    public _PgForeignServersRecord value1(@Nullable Long value) {
        setOid(value);
        return this;
    }

    @Override
    @NotNull
    public _PgForeignServersRecord value2(@Nullable String[] value) {
        setSrvoptions(value);
        return this;
    }

    @Override
    @NotNull
    public _PgForeignServersRecord value3(@Nullable String value) {
        setForeignServerCatalog(value);
        return this;
    }

    @Override
    @NotNull
    public _PgForeignServersRecord value4(@Nullable String value) {
        setForeignServerName(value);
        return this;
    }

    @Override
    @NotNull
    public _PgForeignServersRecord value5(@Nullable String value) {
        setForeignDataWrapperCatalog(value);
        return this;
    }

    @Override
    @NotNull
    public _PgForeignServersRecord value6(@Nullable String value) {
        setForeignDataWrapperName(value);
        return this;
    }

    @Override
    @NotNull
    public _PgForeignServersRecord value7(@Nullable String value) {
        setForeignServerType(value);
        return this;
    }

    @Override
    @NotNull
    public _PgForeignServersRecord value8(@Nullable String value) {
        setForeignServerVersion(value);
        return this;
    }

    @Override
    @NotNull
    public _PgForeignServersRecord value9(@Nullable String value) {
        setAuthorizationIdentifier(value);
        return this;
    }

    @Override
    @NotNull
    public _PgForeignServersRecord values(@Nullable Long value1, @Nullable String[] value2, @Nullable String value3, @Nullable String value4, @Nullable String value5, @Nullable String value6, @Nullable String value7, @Nullable String value8, @Nullable String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached _PgForeignServersRecord
     */
    public _PgForeignServersRecord() {
        super(_PgForeignServers._PG_FOREIGN_SERVERS);
    }

    /**
     * Create a detached, initialised _PgForeignServersRecord
     */
    @ConstructorProperties({ "oid", "srvoptions", "foreignServerCatalog", "foreignServerName", "foreignDataWrapperCatalog", "foreignDataWrapperName", "foreignServerType", "foreignServerVersion", "authorizationIdentifier" })
    public _PgForeignServersRecord(@Nullable Long oid, @Nullable String[] srvoptions, @Nullable String foreignServerCatalog, @Nullable String foreignServerName, @Nullable String foreignDataWrapperCatalog, @Nullable String foreignDataWrapperName, @Nullable String foreignServerType, @Nullable String foreignServerVersion, @Nullable String authorizationIdentifier) {
        super(_PgForeignServers._PG_FOREIGN_SERVERS);

        setOid(oid);
        setSrvoptions(srvoptions);
        setForeignServerCatalog(foreignServerCatalog);
        setForeignServerName(foreignServerName);
        setForeignDataWrapperCatalog(foreignDataWrapperCatalog);
        setForeignDataWrapperName(foreignDataWrapperName);
        setForeignServerType(foreignServerType);
        setForeignServerVersion(foreignServerVersion);
        setAuthorizationIdentifier(authorizationIdentifier);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised _PgForeignServersRecord
     */
    public _PgForeignServersRecord(edu.java.domain.jooq.information_schema.tables.pojos._PgForeignServers value) {
        super(_PgForeignServers._PG_FOREIGN_SERVERS);

        if (value != null) {
            setOid(value.getOid());
            setSrvoptions(value.getSrvoptions());
            setForeignServerCatalog(value.getForeignServerCatalog());
            setForeignServerName(value.getForeignServerName());
            setForeignDataWrapperCatalog(value.getForeignDataWrapperCatalog());
            setForeignDataWrapperName(value.getForeignDataWrapperName());
            setForeignServerType(value.getForeignServerType());
            setForeignServerVersion(value.getForeignServerVersion());
            setAuthorizationIdentifier(value.getAuthorizationIdentifier());
            resetChangedOnNotNull();
        }
    }
}
