/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.information_schema.tables.records;


import edu.java.domain.jooq.information_schema.tables._PgUserMappings;

import java.beans.ConstructorProperties;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.TableRecordImpl;


/**
 * The table <code>information_schema._pg_user_mappings</code>.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class _PgUserMappingsRecord extends TableRecordImpl<_PgUserMappingsRecord> implements Record7<Long, String[], Long, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>information_schema._pg_user_mappings.oid</code>.
     */
    public void setOid(@Nullable Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>information_schema._pg_user_mappings.oid</code>.
     */
    @Nullable
    public Long getOid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>information_schema._pg_user_mappings.umoptions</code>.
     */
    public void setUmoptions(@Nullable String[] value) {
        set(1, value);
    }

    /**
     * Getter for <code>information_schema._pg_user_mappings.umoptions</code>.
     */
    @Nullable
    public String[] getUmoptions() {
        return (String[]) get(1);
    }

    /**
     * Setter for <code>information_schema._pg_user_mappings.umuser</code>.
     */
    public void setUmuser(@Nullable Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>information_schema._pg_user_mappings.umuser</code>.
     */
    @Nullable
    public Long getUmuser() {
        return (Long) get(2);
    }

    /**
     * Setter for
     * <code>information_schema._pg_user_mappings.authorization_identifier</code>.
     */
    public void setAuthorizationIdentifier(@Nullable String value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>information_schema._pg_user_mappings.authorization_identifier</code>.
     */
    @Nullable
    public String getAuthorizationIdentifier() {
        return (String) get(3);
    }

    /**
     * Setter for
     * <code>information_schema._pg_user_mappings.foreign_server_catalog</code>.
     */
    public void setForeignServerCatalog(@Nullable String value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>information_schema._pg_user_mappings.foreign_server_catalog</code>.
     */
    @Nullable
    public String getForeignServerCatalog() {
        return (String) get(4);
    }

    /**
     * Setter for
     * <code>information_schema._pg_user_mappings.foreign_server_name</code>.
     */
    public void setForeignServerName(@Nullable String value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>information_schema._pg_user_mappings.foreign_server_name</code>.
     */
    @Nullable
    public String getForeignServerName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>information_schema._pg_user_mappings.srvowner</code>.
     */
    public void setSrvowner(@Nullable String value) {
        set(6, value);
    }

    /**
     * Getter for <code>information_schema._pg_user_mappings.srvowner</code>.
     */
    @Nullable
    public String getSrvowner() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row7<Long, String[], Long, String, String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row7<Long, String[], Long, String, String, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return _PgUserMappings._PG_USER_MAPPINGS.OID;
    }

    @Override
    @NotNull
    public Field<String[]> field2() {
        return _PgUserMappings._PG_USER_MAPPINGS.UMOPTIONS;
    }

    @Override
    @NotNull
    public Field<Long> field3() {
        return _PgUserMappings._PG_USER_MAPPINGS.UMUSER;
    }

    @Override
    @NotNull
    public Field<String> field4() {
        return _PgUserMappings._PG_USER_MAPPINGS.AUTHORIZATION_IDENTIFIER;
    }

    @Override
    @NotNull
    public Field<String> field5() {
        return _PgUserMappings._PG_USER_MAPPINGS.FOREIGN_SERVER_CATALOG;
    }

    @Override
    @NotNull
    public Field<String> field6() {
        return _PgUserMappings._PG_USER_MAPPINGS.FOREIGN_SERVER_NAME;
    }

    @Override
    @NotNull
    public Field<String> field7() {
        return _PgUserMappings._PG_USER_MAPPINGS.SRVOWNER;
    }

    @Override
    @Nullable
    public Long component1() {
        return getOid();
    }

    @Override
    @Nullable
    public String[] component2() {
        return getUmoptions();
    }

    @Override
    @Nullable
    public Long component3() {
        return getUmuser();
    }

    @Override
    @Nullable
    public String component4() {
        return getAuthorizationIdentifier();
    }

    @Override
    @Nullable
    public String component5() {
        return getForeignServerCatalog();
    }

    @Override
    @Nullable
    public String component6() {
        return getForeignServerName();
    }

    @Override
    @Nullable
    public String component7() {
        return getSrvowner();
    }

    @Override
    @Nullable
    public Long value1() {
        return getOid();
    }

    @Override
    @Nullable
    public String[] value2() {
        return getUmoptions();
    }

    @Override
    @Nullable
    public Long value3() {
        return getUmuser();
    }

    @Override
    @Nullable
    public String value4() {
        return getAuthorizationIdentifier();
    }

    @Override
    @Nullable
    public String value5() {
        return getForeignServerCatalog();
    }

    @Override
    @Nullable
    public String value6() {
        return getForeignServerName();
    }

    @Override
    @Nullable
    public String value7() {
        return getSrvowner();
    }

    @Override
    @NotNull
    public _PgUserMappingsRecord value1(@Nullable Long value) {
        setOid(value);
        return this;
    }

    @Override
    @NotNull
    public _PgUserMappingsRecord value2(@Nullable String[] value) {
        setUmoptions(value);
        return this;
    }

    @Override
    @NotNull
    public _PgUserMappingsRecord value3(@Nullable Long value) {
        setUmuser(value);
        return this;
    }

    @Override
    @NotNull
    public _PgUserMappingsRecord value4(@Nullable String value) {
        setAuthorizationIdentifier(value);
        return this;
    }

    @Override
    @NotNull
    public _PgUserMappingsRecord value5(@Nullable String value) {
        setForeignServerCatalog(value);
        return this;
    }

    @Override
    @NotNull
    public _PgUserMappingsRecord value6(@Nullable String value) {
        setForeignServerName(value);
        return this;
    }

    @Override
    @NotNull
    public _PgUserMappingsRecord value7(@Nullable String value) {
        setSrvowner(value);
        return this;
    }

    @Override
    @NotNull
    public _PgUserMappingsRecord values(@Nullable Long value1, @Nullable String[] value2, @Nullable Long value3, @Nullable String value4, @Nullable String value5, @Nullable String value6, @Nullable String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached _PgUserMappingsRecord
     */
    public _PgUserMappingsRecord() {
        super(_PgUserMappings._PG_USER_MAPPINGS);
    }

    /**
     * Create a detached, initialised _PgUserMappingsRecord
     */
    @ConstructorProperties({ "oid", "umoptions", "umuser", "authorizationIdentifier", "foreignServerCatalog", "foreignServerName", "srvowner" })
    public _PgUserMappingsRecord(@Nullable Long oid, @Nullable String[] umoptions, @Nullable Long umuser, @Nullable String authorizationIdentifier, @Nullable String foreignServerCatalog, @Nullable String foreignServerName, @Nullable String srvowner) {
        super(_PgUserMappings._PG_USER_MAPPINGS);

        setOid(oid);
        setUmoptions(umoptions);
        setUmuser(umuser);
        setAuthorizationIdentifier(authorizationIdentifier);
        setForeignServerCatalog(foreignServerCatalog);
        setForeignServerName(foreignServerName);
        setSrvowner(srvowner);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised _PgUserMappingsRecord
     */
    public _PgUserMappingsRecord(edu.java.domain.jooq.information_schema.tables.pojos._PgUserMappings value) {
        super(_PgUserMappings._PG_USER_MAPPINGS);

        if (value != null) {
            setOid(value.getOid());
            setUmoptions(value.getUmoptions());
            setUmuser(value.getUmuser());
            setAuthorizationIdentifier(value.getAuthorizationIdentifier());
            setForeignServerCatalog(value.getForeignServerCatalog());
            setForeignServerName(value.getForeignServerName());
            setSrvowner(value.getSrvowner());
            resetChangedOnNotNull();
        }
    }
}
