/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.information_schema.tables.records;


import edu.java.domain.jooq.information_schema.tables.ForeignDataWrapperOptions;

import java.beans.ConstructorProperties;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ForeignDataWrapperOptionsRecord extends TableRecordImpl<ForeignDataWrapperOptionsRecord> implements Record4<String, String, String, String> {

    private static final long serialVersionUID = 1L;

    public void setForeignDataWrapperCatalog(@Nullable String value) {
        set(0, value);
    }

    @Nullable
    public String getForeignDataWrapperCatalog() {
        return (String) get(0);
    }

    public void setForeignDataWrapperName(@Nullable String value) {
        set(1, value);
    }

    @Nullable
    public String getForeignDataWrapperName() {
        return (String) get(1);
    }

    public void setOptionName(@Nullable String value) {
        set(2, value);
    }

    @Nullable
    public String getOptionName() {
        return (String) get(2);
    }

    public void setOptionValue(@Nullable String value) {
        set(3, value);
    }

    @Nullable
    public String getOptionValue() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row4<String, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row4<String, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<String> field1() {
        return ForeignDataWrapperOptions.FOREIGN_DATA_WRAPPER_OPTIONS.FOREIGN_DATA_WRAPPER_CATALOG;
    }

    @Override
    @NotNull
    public Field<String> field2() {
        return ForeignDataWrapperOptions.FOREIGN_DATA_WRAPPER_OPTIONS.FOREIGN_DATA_WRAPPER_NAME;
    }

    @Override
    @NotNull
    public Field<String> field3() {
        return ForeignDataWrapperOptions.FOREIGN_DATA_WRAPPER_OPTIONS.OPTION_NAME;
    }

    @Override
    @NotNull
    public Field<String> field4() {
        return ForeignDataWrapperOptions.FOREIGN_DATA_WRAPPER_OPTIONS.OPTION_VALUE;
    }

    @Override
    @Nullable
    public String component1() {
        return getForeignDataWrapperCatalog();
    }

    @Override
    @Nullable
    public String component2() {
        return getForeignDataWrapperName();
    }

    @Override
    @Nullable
    public String component3() {
        return getOptionName();
    }

    @Override
    @Nullable
    public String component4() {
        return getOptionValue();
    }

    @Override
    @Nullable
    public String value1() {
        return getForeignDataWrapperCatalog();
    }

    @Override
    @Nullable
    public String value2() {
        return getForeignDataWrapperName();
    }

    @Override
    @Nullable
    public String value3() {
        return getOptionName();
    }

    @Override
    @Nullable
    public String value4() {
        return getOptionValue();
    }

    @Override
    @NotNull
    public ForeignDataWrapperOptionsRecord value1(@Nullable String value) {
        setForeignDataWrapperCatalog(value);
        return this;
    }

    @Override
    @NotNull
    public ForeignDataWrapperOptionsRecord value2(@Nullable String value) {
        setForeignDataWrapperName(value);
        return this;
    }

    @Override
    @NotNull
    public ForeignDataWrapperOptionsRecord value3(@Nullable String value) {
        setOptionName(value);
        return this;
    }

    @Override
    @NotNull
    public ForeignDataWrapperOptionsRecord value4(@Nullable String value) {
        setOptionValue(value);
        return this;
    }

    @Override
    @NotNull
    public ForeignDataWrapperOptionsRecord values(@Nullable String value1, @Nullable String value2, @Nullable String value3, @Nullable String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    public ForeignDataWrapperOptionsRecord() {
        super(ForeignDataWrapperOptions.FOREIGN_DATA_WRAPPER_OPTIONS);
    }

    @ConstructorProperties({ "foreignDataWrapperCatalog", "foreignDataWrapperName", "optionName", "optionValue" })
    public ForeignDataWrapperOptionsRecord(@Nullable String foreignDataWrapperCatalog, @Nullable String foreignDataWrapperName, @Nullable String optionName, @Nullable String optionValue) {
        super(ForeignDataWrapperOptions.FOREIGN_DATA_WRAPPER_OPTIONS);

        setForeignDataWrapperCatalog(foreignDataWrapperCatalog);
        setForeignDataWrapperName(foreignDataWrapperName);
        setOptionName(optionName);
        setOptionValue(optionValue);
        resetChangedOnNotNull();
    }

    public ForeignDataWrapperOptionsRecord(edu.java.domain.jooq.information_schema.tables.pojos.ForeignDataWrapperOptions value) {
        super(ForeignDataWrapperOptions.FOREIGN_DATA_WRAPPER_OPTIONS);

        if (value != null) {
            setForeignDataWrapperCatalog(value.getForeignDataWrapperCatalog());
            setForeignDataWrapperName(value.getForeignDataWrapperName());
            setOptionName(value.getOptionName());
            setOptionValue(value.getOptionValue());
            resetChangedOnNotNull();
        }
    }
}
