/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.information_schema.tables.records;


import edu.java.domain.jooq.information_schema.tables.RoutineSequenceUsage;

import java.beans.ConstructorProperties;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RoutineSequenceUsageRecord extends TableRecordImpl<RoutineSequenceUsageRecord> implements Record9<String, String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>information_schema.routine_sequence_usage.specific_catalog</code>.
     */
    public void setSpecificCatalog(@Nullable String value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>information_schema.routine_sequence_usage.specific_catalog</code>.
     */
    @Nullable
    public String getSpecificCatalog() {
        return (String) get(0);
    }

    /**
     * Setter for
     * <code>information_schema.routine_sequence_usage.specific_schema</code>.
     */
    public void setSpecificSchema(@Nullable String value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>information_schema.routine_sequence_usage.specific_schema</code>.
     */
    @Nullable
    public String getSpecificSchema() {
        return (String) get(1);
    }

    /**
     * Setter for
     * <code>information_schema.routine_sequence_usage.specific_name</code>.
     */
    public void setSpecificName(@Nullable String value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>information_schema.routine_sequence_usage.specific_name</code>.
     */
    @Nullable
    public String getSpecificName() {
        return (String) get(2);
    }

    /**
     * Setter for
     * <code>information_schema.routine_sequence_usage.routine_catalog</code>.
     */
    public void setRoutineCatalog(@Nullable String value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>information_schema.routine_sequence_usage.routine_catalog</code>.
     */
    @Nullable
    public String getRoutineCatalog() {
        return (String) get(3);
    }

    /**
     * Setter for
     * <code>information_schema.routine_sequence_usage.routine_schema</code>.
     */
    public void setRoutineSchema(@Nullable String value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>information_schema.routine_sequence_usage.routine_schema</code>.
     */
    @Nullable
    public String getRoutineSchema() {
        return (String) get(4);
    }

    /**
     * Setter for
     * <code>information_schema.routine_sequence_usage.routine_name</code>.
     */
    public void setRoutineName(@Nullable String value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>information_schema.routine_sequence_usage.routine_name</code>.
     */
    @Nullable
    public String getRoutineName() {
        return (String) get(5);
    }

    /**
     * Setter for
     * <code>information_schema.routine_sequence_usage.sequence_catalog</code>.
     */
    public void setSequenceCatalog(@Nullable String value) {
        set(6, value);
    }

    /**
     * Getter for
     * <code>information_schema.routine_sequence_usage.sequence_catalog</code>.
     */
    @Nullable
    public String getSequenceCatalog() {
        return (String) get(6);
    }

    /**
     * Setter for
     * <code>information_schema.routine_sequence_usage.sequence_schema</code>.
     */
    public void setSequenceSchema(@Nullable String value) {
        set(7, value);
    }

    /**
     * Getter for
     * <code>information_schema.routine_sequence_usage.sequence_schema</code>.
     */
    @Nullable
    public String getSequenceSchema() {
        return (String) get(7);
    }

    /**
     * Setter for
     * <code>information_schema.routine_sequence_usage.sequence_name</code>.
     */
    public void setSequenceName(@Nullable String value) {
        set(8, value);
    }

    /**
     * Getter for
     * <code>information_schema.routine_sequence_usage.sequence_name</code>.
     */
    @Nullable
    public String getSequenceName() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row9<String, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row9<String, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<String> field1() {
        return RoutineSequenceUsage.ROUTINE_SEQUENCE_USAGE.SPECIFIC_CATALOG;
    }

    @Override
    @NotNull
    public Field<String> field2() {
        return RoutineSequenceUsage.ROUTINE_SEQUENCE_USAGE.SPECIFIC_SCHEMA;
    }

    @Override
    @NotNull
    public Field<String> field3() {
        return RoutineSequenceUsage.ROUTINE_SEQUENCE_USAGE.SPECIFIC_NAME;
    }

    @Override
    @NotNull
    public Field<String> field4() {
        return RoutineSequenceUsage.ROUTINE_SEQUENCE_USAGE.ROUTINE_CATALOG;
    }

    @Override
    @NotNull
    public Field<String> field5() {
        return RoutineSequenceUsage.ROUTINE_SEQUENCE_USAGE.ROUTINE_SCHEMA;
    }

    @Override
    @NotNull
    public Field<String> field6() {
        return RoutineSequenceUsage.ROUTINE_SEQUENCE_USAGE.ROUTINE_NAME;
    }

    @Override
    @NotNull
    public Field<String> field7() {
        return RoutineSequenceUsage.ROUTINE_SEQUENCE_USAGE.SEQUENCE_CATALOG;
    }

    @Override
    @NotNull
    public Field<String> field8() {
        return RoutineSequenceUsage.ROUTINE_SEQUENCE_USAGE.SEQUENCE_SCHEMA;
    }

    @Override
    @NotNull
    public Field<String> field9() {
        return RoutineSequenceUsage.ROUTINE_SEQUENCE_USAGE.SEQUENCE_NAME;
    }

    @Override
    @Nullable
    public String component1() {
        return getSpecificCatalog();
    }

    @Override
    @Nullable
    public String component2() {
        return getSpecificSchema();
    }

    @Override
    @Nullable
    public String component3() {
        return getSpecificName();
    }

    @Override
    @Nullable
    public String component4() {
        return getRoutineCatalog();
    }

    @Override
    @Nullable
    public String component5() {
        return getRoutineSchema();
    }

    @Override
    @Nullable
    public String component6() {
        return getRoutineName();
    }

    @Override
    @Nullable
    public String component7() {
        return getSequenceCatalog();
    }

    @Override
    @Nullable
    public String component8() {
        return getSequenceSchema();
    }

    @Override
    @Nullable
    public String component9() {
        return getSequenceName();
    }

    @Override
    @Nullable
    public String value1() {
        return getSpecificCatalog();
    }

    @Override
    @Nullable
    public String value2() {
        return getSpecificSchema();
    }

    @Override
    @Nullable
    public String value3() {
        return getSpecificName();
    }

    @Override
    @Nullable
    public String value4() {
        return getRoutineCatalog();
    }

    @Override
    @Nullable
    public String value5() {
        return getRoutineSchema();
    }

    @Override
    @Nullable
    public String value6() {
        return getRoutineName();
    }

    @Override
    @Nullable
    public String value7() {
        return getSequenceCatalog();
    }

    @Override
    @Nullable
    public String value8() {
        return getSequenceSchema();
    }

    @Override
    @Nullable
    public String value9() {
        return getSequenceName();
    }

    @Override
    @NotNull
    public RoutineSequenceUsageRecord value1(@Nullable String value) {
        setSpecificCatalog(value);
        return this;
    }

    @Override
    @NotNull
    public RoutineSequenceUsageRecord value2(@Nullable String value) {
        setSpecificSchema(value);
        return this;
    }

    @Override
    @NotNull
    public RoutineSequenceUsageRecord value3(@Nullable String value) {
        setSpecificName(value);
        return this;
    }

    @Override
    @NotNull
    public RoutineSequenceUsageRecord value4(@Nullable String value) {
        setRoutineCatalog(value);
        return this;
    }

    @Override
    @NotNull
    public RoutineSequenceUsageRecord value5(@Nullable String value) {
        setRoutineSchema(value);
        return this;
    }

    @Override
    @NotNull
    public RoutineSequenceUsageRecord value6(@Nullable String value) {
        setRoutineName(value);
        return this;
    }

    @Override
    @NotNull
    public RoutineSequenceUsageRecord value7(@Nullable String value) {
        setSequenceCatalog(value);
        return this;
    }

    @Override
    @NotNull
    public RoutineSequenceUsageRecord value8(@Nullable String value) {
        setSequenceSchema(value);
        return this;
    }

    @Override
    @NotNull
    public RoutineSequenceUsageRecord value9(@Nullable String value) {
        setSequenceName(value);
        return this;
    }

    @Override
    @NotNull
    public RoutineSequenceUsageRecord values(@Nullable String value1, @Nullable String value2, @Nullable String value3, @Nullable String value4, @Nullable String value5, @Nullable String value6, @Nullable String value7, @Nullable String value8, @Nullable String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RoutineSequenceUsageRecord
     */
    public RoutineSequenceUsageRecord() {
        super(RoutineSequenceUsage.ROUTINE_SEQUENCE_USAGE);
    }

    /**
     * Create a detached, initialised RoutineSequenceUsageRecord
     */
    @ConstructorProperties({ "specificCatalog", "specificSchema", "specificName", "routineCatalog", "routineSchema", "routineName", "sequenceCatalog", "sequenceSchema", "sequenceName" })
    public RoutineSequenceUsageRecord(@Nullable String specificCatalog, @Nullable String specificSchema, @Nullable String specificName, @Nullable String routineCatalog, @Nullable String routineSchema, @Nullable String routineName, @Nullable String sequenceCatalog, @Nullable String sequenceSchema, @Nullable String sequenceName) {
        super(RoutineSequenceUsage.ROUTINE_SEQUENCE_USAGE);

        setSpecificCatalog(specificCatalog);
        setSpecificSchema(specificSchema);
        setSpecificName(specificName);
        setRoutineCatalog(routineCatalog);
        setRoutineSchema(routineSchema);
        setRoutineName(routineName);
        setSequenceCatalog(sequenceCatalog);
        setSequenceSchema(sequenceSchema);
        setSequenceName(sequenceName);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised RoutineSequenceUsageRecord
     */
    public RoutineSequenceUsageRecord(edu.java.domain.jooq.information_schema.tables.pojos.RoutineSequenceUsage value) {
        super(RoutineSequenceUsage.ROUTINE_SEQUENCE_USAGE);

        if (value != null) {
            setSpecificCatalog(value.getSpecificCatalog());
            setSpecificSchema(value.getSpecificSchema());
            setSpecificName(value.getSpecificName());
            setRoutineCatalog(value.getRoutineCatalog());
            setRoutineSchema(value.getRoutineSchema());
            setRoutineName(value.getRoutineName());
            setSequenceCatalog(value.getSequenceCatalog());
            setSequenceSchema(value.getSequenceSchema());
            setSequenceName(value.getSequenceName());
            resetChangedOnNotNull();
        }
    }
}
