/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.information_schema.tables.records;


import edu.java.domain.jooq.information_schema.tables.UdtPrivileges;

import jakarta.validation.constraints.Size;

import java.beans.ConstructorProperties;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.TableRecordImpl;


@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UdtPrivilegesRecord extends TableRecordImpl<UdtPrivilegesRecord> implements Record7<String, String, String, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    public void setGrantor(@Nullable String value) {
        set(0, value);
    }

    @Nullable
    public String getGrantor() {
        return (String) get(0);
    }

    public void setGrantee(@Nullable String value) {
        set(1, value);
    }

    @Nullable
    public String getGrantee() {
        return (String) get(1);
    }

    public void setUdtCatalog(@Nullable String value) {
        set(2, value);
    }

    @Nullable
    public String getUdtCatalog() {
        return (String) get(2);
    }

    public void setUdtSchema(@Nullable String value) {
        set(3, value);
    }

    @Nullable
    public String getUdtSchema() {
        return (String) get(3);
    }

    public void setUdtName(@Nullable String value) {
        set(4, value);
    }

    @Nullable
    public String getUdtName() {
        return (String) get(4);
    }

    public void setPrivilegeType(@Nullable String value) {
        set(5, value);
    }

    @Nullable
    public String getPrivilegeType() {
        return (String) get(5);
    }

    public void setIsGrantable(@Nullable String value) {
        set(6, value);
    }

    @Size(max = 3)
    @Nullable
    public String getIsGrantable() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row7<String, String, String, String, String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row7<String, String, String, String, String, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<String> field1() {
        return UdtPrivileges.UDT_PRIVILEGES.GRANTOR;
    }

    @Override
    @NotNull
    public Field<String> field2() {
        return UdtPrivileges.UDT_PRIVILEGES.GRANTEE;
    }

    @Override
    @NotNull
    public Field<String> field3() {
        return UdtPrivileges.UDT_PRIVILEGES.UDT_CATALOG;
    }

    @Override
    @NotNull
    public Field<String> field4() {
        return UdtPrivileges.UDT_PRIVILEGES.UDT_SCHEMA;
    }

    @Override
    @NotNull
    public Field<String> field5() {
        return UdtPrivileges.UDT_PRIVILEGES.UDT_NAME;
    }

    @Override
    @NotNull
    public Field<String> field6() {
        return UdtPrivileges.UDT_PRIVILEGES.PRIVILEGE_TYPE;
    }

    @Override
    @NotNull
    public Field<String> field7() {
        return UdtPrivileges.UDT_PRIVILEGES.IS_GRANTABLE;
    }

    @Override
    @Nullable
    public String component1() {
        return getGrantor();
    }

    @Override
    @Nullable
    public String component2() {
        return getGrantee();
    }

    @Override
    @Nullable
    public String component3() {
        return getUdtCatalog();
    }

    @Override
    @Nullable
    public String component4() {
        return getUdtSchema();
    }

    @Override
    @Nullable
    public String component5() {
        return getUdtName();
    }

    @Override
    @Nullable
    public String component6() {
        return getPrivilegeType();
    }

    @Override
    @Nullable
    public String component7() {
        return getIsGrantable();
    }

    @Override
    @Nullable
    public String value1() {
        return getGrantor();
    }

    @Override
    @Nullable
    public String value2() {
        return getGrantee();
    }

    @Override
    @Nullable
    public String value3() {
        return getUdtCatalog();
    }

    @Override
    @Nullable
    public String value4() {
        return getUdtSchema();
    }

    @Override
    @Nullable
    public String value5() {
        return getUdtName();
    }

    @Override
    @Nullable
    public String value6() {
        return getPrivilegeType();
    }

    @Override
    @Nullable
    public String value7() {
        return getIsGrantable();
    }

    @Override
    @NotNull
    public UdtPrivilegesRecord value1(@Nullable String value) {
        setGrantor(value);
        return this;
    }

    @Override
    @NotNull
    public UdtPrivilegesRecord value2(@Nullable String value) {
        setGrantee(value);
        return this;
    }

    @Override
    @NotNull
    public UdtPrivilegesRecord value3(@Nullable String value) {
        setUdtCatalog(value);
        return this;
    }

    @Override
    @NotNull
    public UdtPrivilegesRecord value4(@Nullable String value) {
        setUdtSchema(value);
        return this;
    }

    @Override
    @NotNull
    public UdtPrivilegesRecord value5(@Nullable String value) {
        setUdtName(value);
        return this;
    }

    @Override
    @NotNull
    public UdtPrivilegesRecord value6(@Nullable String value) {
        setPrivilegeType(value);
        return this;
    }

    @Override
    @NotNull
    public UdtPrivilegesRecord value7(@Nullable String value) {
        setIsGrantable(value);
        return this;
    }

    @Override
    @NotNull
    public UdtPrivilegesRecord values(@Nullable String value1, @Nullable String value2, @Nullable String value3, @Nullable String value4, @Nullable String value5, @Nullable String value6, @Nullable String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    public UdtPrivilegesRecord() {
        super(UdtPrivileges.UDT_PRIVILEGES);
    }

    @ConstructorProperties({ "grantor", "grantee", "udtCatalog", "udtSchema", "udtName", "privilegeType", "isGrantable" })
    public UdtPrivilegesRecord(@Nullable String grantor, @Nullable String grantee, @Nullable String udtCatalog, @Nullable String udtSchema, @Nullable String udtName, @Nullable String privilegeType, @Nullable String isGrantable) {
        super(UdtPrivileges.UDT_PRIVILEGES);

        setGrantor(grantor);
        setGrantee(grantee);
        setUdtCatalog(udtCatalog);
        setUdtSchema(udtSchema);
        setUdtName(udtName);
        setPrivilegeType(privilegeType);
        setIsGrantable(isGrantable);
        resetChangedOnNotNull();
    }

    public UdtPrivilegesRecord(edu.java.domain.jooq.information_schema.tables.pojos.UdtPrivileges value) {
        super(UdtPrivileges.UDT_PRIVILEGES);

        if (value != null) {
            setGrantor(value.getGrantor());
            setGrantee(value.getGrantee());
            setUdtCatalog(value.getUdtCatalog());
            setUdtSchema(value.getUdtSchema());
            setUdtName(value.getUdtName());
            setPrivilegeType(value.getPrivilegeType());
            setIsGrantable(value.getIsGrantable());
            resetChangedOnNotNull();
        }
    }
}
