/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.pg_catalog.routines;


import edu.java.domain.jooq.pg_catalog.PgCatalog;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.JSON;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JsonObjectField extends AbstractRoutine<JSON> {

    private static final long serialVersionUID = 1L;

    public static final Parameter<JSON> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", SQLDataType.JSON, false, false);

    public static final Parameter<JSON> FROM_JSON = Internal.createParameter("from_json", SQLDataType.JSON, false, false);

    public static final Parameter<String> FIELD_NAME = Internal.createParameter("field_name", SQLDataType.CLOB, false, false);

    public JsonObjectField() {
        super("json_object_field", PgCatalog.PG_CATALOG, SQLDataType.JSON);

        setReturnParameter(RETURN_VALUE);
        addInParameter(FROM_JSON);
        addInParameter(FIELD_NAME);
    }

    public void setFromJson(JSON value) {
        setValue(FROM_JSON, value);
    }

    public void setFromJson(Field<JSON> field) {
        setField(FROM_JSON, field);
    }

    public void setFieldName(String value) {
        setValue(FIELD_NAME, value);
    }

    public void setFieldName(Field<String> field) {
        setField(FIELD_NAME, field);
    }
}
