/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.pg_catalog.tables.records;


import edu.java.domain.jooq.pg_catalog.tables.JsonbToRecordset;

import java.beans.ConstructorProperties;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.Nullable;
import org.jooq.Record;
import org.jooq.impl.TableRecordImpl;


@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JsonbToRecordsetRecord extends TableRecordImpl<JsonbToRecordsetRecord> {

    private static final long serialVersionUID = 1L;

    public void setJsonbToRecordset(@Nullable Record value) {
        set(0, value);
    }

    @Nullable
    public Record getJsonbToRecordset() {
        return (Record) get(0);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    public JsonbToRecordsetRecord() {
        super(JsonbToRecordset.JSONB_TO_RECORDSET);
    }

    @ConstructorProperties({ "jsonbToRecordset" })
    public JsonbToRecordsetRecord(@Nullable Record jsonbToRecordset) {
        super(JsonbToRecordset.JSONB_TO_RECORDSET);

        setJsonbToRecordset(jsonbToRecordset);
        resetChangedOnNotNull();
    }

    public JsonbToRecordsetRecord(edu.java.domain.jooq.pg_catalog.tables.pojos.JsonbToRecordset value) {
        super(JsonbToRecordset.JSONB_TO_RECORDSET);

        if (value != null) {
            setJsonbToRecordset(value.getJsonbToRecordset());
            resetChangedOnNotNull();
        }
    }
}
