/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.pg_catalog.tables.records;


import edu.java.domain.jooq.pg_catalog.tables.JsonToRecordset;

import java.beans.ConstructorProperties;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.Nullable;
import org.jooq.Record;
import org.jooq.impl.TableRecordImpl;


@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JsonToRecordsetRecord extends TableRecordImpl<JsonToRecordsetRecord> {

    private static final long serialVersionUID = 1L;

    public void setJsonToRecordset(@Nullable Record value) {
        set(0, value);
    }

    @Nullable
    public Record getJsonToRecordset() {
        return (Record) get(0);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    public JsonToRecordsetRecord() {
        super(JsonToRecordset.JSON_TO_RECORDSET);
    }

    @ConstructorProperties({ "jsonToRecordset" })
    public JsonToRecordsetRecord(@Nullable Record jsonToRecordset) {
        super(JsonToRecordset.JSON_TO_RECORDSET);

        setJsonToRecordset(jsonToRecordset);
        resetChangedOnNotNull();
    }

    public JsonToRecordsetRecord(edu.java.domain.jooq.pg_catalog.tables.pojos.JsonToRecordset value) {
        super(JsonToRecordset.JSON_TO_RECORDSET);

        if (value != null) {
            setJsonToRecordset(value.getJsonToRecordset());
            resetChangedOnNotNull();
        }
    }
}
