/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.pg_catalog.tables.records;


import edu.java.domain.jooq.pg_catalog.tables.JsonObjectKeys;

import java.beans.ConstructorProperties;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.Nullable;
import org.jooq.impl.TableRecordImpl;


@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JsonObjectKeysRecord extends TableRecordImpl<JsonObjectKeysRecord> {

    private static final long serialVersionUID = 1L;

    public void setJsonObjectKeys(@Nullable String value) {
        set(0, value);
    }

    @Nullable
    public String getJsonObjectKeys() {
        return (String) get(0);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    public JsonObjectKeysRecord() {
        super(JsonObjectKeys.JSON_OBJECT_KEYS);
    }

    @ConstructorProperties({ "jsonObjectKeys" })
    public JsonObjectKeysRecord(@Nullable String jsonObjectKeys) {
        super(JsonObjectKeys.JSON_OBJECT_KEYS);

        setJsonObjectKeys(jsonObjectKeys);
        resetChangedOnNotNull();
    }

    public JsonObjectKeysRecord(edu.java.domain.jooq.pg_catalog.tables.pojos.JsonObjectKeys value) {
        super(JsonObjectKeys.JSON_OBJECT_KEYS);

        if (value != null) {
            setJsonObjectKeys(value.getJsonObjectKeys());
            resetChangedOnNotNull();
        }
    }
}
