/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.pg_catalog.tables.records;


import edu.java.domain.jooq.pg_catalog.tables.PgAttrdef;

import java.beans.ConstructorProperties;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PgAttrdefRecord extends UpdatableRecordImpl<PgAttrdefRecord> implements Record4<Long, Long, Short, Object> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>pg_catalog.pg_attrdef.oid</code>.
     */
    public void setOid(@NotNull Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_attrdef.oid</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getOid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>pg_catalog.pg_attrdef.adrelid</code>.
     */
    public void setAdrelid(@NotNull Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_attrdef.adrelid</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getAdrelid() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>pg_catalog.pg_attrdef.adnum</code>.
     */
    public void setAdnum(@NotNull Short value) {
        set(2, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_attrdef.adnum</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Short getAdnum() {
        return (Short) get(2);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public void setAdbin(@NotNull Object value) {
        set(3, value);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Object getAdbin() {
        return get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row4<Long, Long, Short, Object> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row4<Long, Long, Short, Object> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return PgAttrdef.PG_ATTRDEF.OID;
    }

    @Override
    @NotNull
    public Field<Long> field2() {
        return PgAttrdef.PG_ATTRDEF.ADRELID;
    }

    @Override
    @NotNull
    public Field<Short> field3() {
        return PgAttrdef.PG_ATTRDEF.ADNUM;
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Override
    @NotNull
    public Field<Object> field4() {
        return PgAttrdef.PG_ATTRDEF.ADBIN;
    }

    @Override
    @NotNull
    public Long component1() {
        return getOid();
    }

    @Override
    @NotNull
    public Long component2() {
        return getAdrelid();
    }

    @Override
    @NotNull
    public Short component3() {
        return getAdnum();
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Override
    @NotNull
    public Object component4() {
        return getAdbin();
    }

    @Override
    @NotNull
    public Long value1() {
        return getOid();
    }

    @Override
    @NotNull
    public Long value2() {
        return getAdrelid();
    }

    @Override
    @NotNull
    public Short value3() {
        return getAdnum();
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Override
    @NotNull
    public Object value4() {
        return getAdbin();
    }

    @Override
    @NotNull
    public PgAttrdefRecord value1(@NotNull Long value) {
        setOid(value);
        return this;
    }

    @Override
    @NotNull
    public PgAttrdefRecord value2(@NotNull Long value) {
        setAdrelid(value);
        return this;
    }

    @Override
    @NotNull
    public PgAttrdefRecord value3(@NotNull Short value) {
        setAdnum(value);
        return this;
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Override
    @NotNull
    public PgAttrdefRecord value4(@NotNull Object value) {
        setAdbin(value);
        return this;
    }

    @Override
    @NotNull
    public PgAttrdefRecord values(@NotNull Long value1, @NotNull Long value2, @NotNull Short value3, @NotNull Object value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PgAttrdefRecord
     */
    public PgAttrdefRecord() {
        super(PgAttrdef.PG_ATTRDEF);
    }

    /**
     * Create a detached, initialised PgAttrdefRecord
     */
    @ConstructorProperties({ "oid", "adrelid", "adnum", "adbin" })
    public PgAttrdefRecord(@NotNull Long oid, @NotNull Long adrelid, @NotNull Short adnum, @NotNull Object adbin) {
        super(PgAttrdef.PG_ATTRDEF);

        setOid(oid);
        setAdrelid(adrelid);
        setAdnum(adnum);
        setAdbin(adbin);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised PgAttrdefRecord
     */
    public PgAttrdefRecord(edu.java.domain.jooq.pg_catalog.tables.pojos.PgAttrdef value) {
        super(PgAttrdef.PG_ATTRDEF);

        if (value != null) {
            setOid(value.getOid());
            setAdrelid(value.getAdrelid());
            setAdnum(value.getAdnum());
            setAdbin(value.getAdbin());
            resetChangedOnNotNull();
        }
    }
}
