/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.pg_catalog.tables.records;


import edu.java.domain.jooq.pg_catalog.tables.PgCast;

import java.beans.ConstructorProperties;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PgCastRecord extends UpdatableRecordImpl<PgCastRecord> implements Record6<Long, Long, Long, Long, String, String> {

    private static final long serialVersionUID = 1L;

    public void setOid(@NotNull Long value) {
        set(0, value);
    }

    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getOid() {
        return (Long) get(0);
    }

    public void setCastsource(@NotNull Long value) {
        set(1, value);
    }

    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getCastsource() {
        return (Long) get(1);
    }

    public void setCasttarget(@NotNull Long value) {
        set(2, value);
    }

    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getCasttarget() {
        return (Long) get(2);
    }

    public void setCastfunc(@NotNull Long value) {
        set(3, value);
    }

    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getCastfunc() {
        return (Long) get(3);
    }

    public void setCastcontext(@NotNull String value) {
        set(4, value);
    }

    @jakarta.validation.constraints.NotNull
    @NotNull
    public String getCastcontext() {
        return (String) get(4);
    }

    public void setCastmethod(@NotNull String value) {
        set(5, value);
    }

    @jakarta.validation.constraints.NotNull
    @NotNull
    public String getCastmethod() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row6<Long, Long, Long, Long, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row6<Long, Long, Long, Long, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return PgCast.PG_CAST.OID;
    }

    @Override
    @NotNull
    public Field<Long> field2() {
        return PgCast.PG_CAST.CASTSOURCE;
    }

    @Override
    @NotNull
    public Field<Long> field3() {
        return PgCast.PG_CAST.CASTTARGET;
    }

    @Override
    @NotNull
    public Field<Long> field4() {
        return PgCast.PG_CAST.CASTFUNC;
    }

    @Override
    @NotNull
    public Field<String> field5() {
        return PgCast.PG_CAST.CASTCONTEXT;
    }

    @Override
    @NotNull
    public Field<String> field6() {
        return PgCast.PG_CAST.CASTMETHOD;
    }

    @Override
    @NotNull
    public Long component1() {
        return getOid();
    }

    @Override
    @NotNull
    public Long component2() {
        return getCastsource();
    }

    @Override
    @NotNull
    public Long component3() {
        return getCasttarget();
    }

    @Override
    @NotNull
    public Long component4() {
        return getCastfunc();
    }

    @Override
    @NotNull
    public String component5() {
        return getCastcontext();
    }

    @Override
    @NotNull
    public String component6() {
        return getCastmethod();
    }

    @Override
    @NotNull
    public Long value1() {
        return getOid();
    }

    @Override
    @NotNull
    public Long value2() {
        return getCastsource();
    }

    @Override
    @NotNull
    public Long value3() {
        return getCasttarget();
    }

    @Override
    @NotNull
    public Long value4() {
        return getCastfunc();
    }

    @Override
    @NotNull
    public String value5() {
        return getCastcontext();
    }

    @Override
    @NotNull
    public String value6() {
        return getCastmethod();
    }

    @Override
    @NotNull
    public PgCastRecord value1(@NotNull Long value) {
        setOid(value);
        return this;
    }

    @Override
    @NotNull
    public PgCastRecord value2(@NotNull Long value) {
        setCastsource(value);
        return this;
    }

    @Override
    @NotNull
    public PgCastRecord value3(@NotNull Long value) {
        setCasttarget(value);
        return this;
    }

    @Override
    @NotNull
    public PgCastRecord value4(@NotNull Long value) {
        setCastfunc(value);
        return this;
    }

    @Override
    @NotNull
    public PgCastRecord value5(@NotNull String value) {
        setCastcontext(value);
        return this;
    }

    @Override
    @NotNull
    public PgCastRecord value6(@NotNull String value) {
        setCastmethod(value);
        return this;
    }

    @Override
    @NotNull
    public PgCastRecord values(@NotNull Long value1, @NotNull Long value2, @NotNull Long value3, @NotNull Long value4, @NotNull String value5, @NotNull String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    public PgCastRecord() {
        super(PgCast.PG_CAST);
    }

    @ConstructorProperties({ "oid", "castsource", "casttarget", "castfunc", "castcontext", "castmethod" })
    public PgCastRecord(@NotNull Long oid, @NotNull Long castsource, @NotNull Long casttarget, @NotNull Long castfunc, @NotNull String castcontext, @NotNull String castmethod) {
        super(PgCast.PG_CAST);

        setOid(oid);
        setCastsource(castsource);
        setCasttarget(casttarget);
        setCastfunc(castfunc);
        setCastcontext(castcontext);
        setCastmethod(castmethod);
        resetChangedOnNotNull();
    }

    public PgCastRecord(edu.java.domain.jooq.pg_catalog.tables.pojos.PgCast value) {
        super(PgCast.PG_CAST);

        if (value != null) {
            setOid(value.getOid());
            setCastsource(value.getCastsource());
            setCasttarget(value.getCasttarget());
            setCastfunc(value.getCastfunc());
            setCastcontext(value.getCastcontext());
            setCastmethod(value.getCastmethod());
            resetChangedOnNotNull();
        }
    }
}
