/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.pg_catalog.tables.records;


import edu.java.domain.jooq.pg_catalog.tables.PgMcvListItems;

import java.beans.ConstructorProperties;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.Nullable;
import org.jooq.impl.TableRecordImpl;


@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PgMcvListItemsRecord extends TableRecordImpl<PgMcvListItemsRecord> {

    private static final long serialVersionUID = 1L;

    public void setIndex(@Nullable Integer value) {
        set(0, value);
    }

    @Nullable
    public Integer getIndex() {
        return (Integer) get(0);
    }

    public void setValues(@Nullable String[] value) {
        set(1, value);
    }

    @Nullable
    public String[] getValues() {
        return (String[]) get(1);
    }

    public void setNulls(@Nullable Boolean[] value) {
        set(2, value);
    }

    @Nullable
    public Boolean[] getNulls() {
        return (Boolean[]) get(2);
    }

    public void setFrequency(@Nullable Double value) {
        set(3, value);
    }

    @Nullable
    public Double getFrequency() {
        return (Double) get(3);
    }

    public void setBaseFrequency(@Nullable Double value) {
        set(4, value);
    }

    @Nullable
    public Double getBaseFrequency() {
        return (Double) get(4);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    public PgMcvListItemsRecord() {
        super(PgMcvListItems.PG_MCV_LIST_ITEMS);
    }

    @ConstructorProperties({ "index", "values", "nulls", "frequency", "baseFrequency" })
    public PgMcvListItemsRecord(@Nullable Integer index, @Nullable String[] values, @Nullable Boolean[] nulls, @Nullable Double frequency, @Nullable Double baseFrequency) {
        super(PgMcvListItems.PG_MCV_LIST_ITEMS);

        setIndex(index);
        setValues(values);
        setNulls(nulls);
        setFrequency(frequency);
        setBaseFrequency(baseFrequency);
        resetChangedOnNotNull();
    }

    public PgMcvListItemsRecord(edu.java.domain.jooq.pg_catalog.tables.pojos.PgMcvListItems value) {
        super(PgMcvListItems.PG_MCV_LIST_ITEMS);

        if (value != null) {
            setIndex(value.getIndex());
            setValues(value.getValues());
            setNulls(value.getNulls());
            setFrequency(value.getFrequency());
            setBaseFrequency(value.getBaseFrequency());
            resetChangedOnNotNull();
        }
    }
}
