/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.pg_catalog.tables.records;


import edu.java.domain.jooq.pg_catalog.tables.PgPartitionTree;

import java.beans.ConstructorProperties;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PgPartitionTreeRecord extends TableRecordImpl<PgPartitionTreeRecord> implements Record4<Object, Object, Boolean, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public void setRelid(@Nullable Object value) {
        set(0, value);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Nullable
    public Object getRelid() {
        return get(0);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public void setParentrelid(@Nullable Object value) {
        set(1, value);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Nullable
    public Object getParentrelid() {
        return get(1);
    }

    /**
     * Setter for <code>pg_catalog.pg_partition_tree.isleaf</code>.
     */
    public void setIsleaf(@Nullable Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_partition_tree.isleaf</code>.
     */
    @Nullable
    public Boolean getIsleaf() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>pg_catalog.pg_partition_tree.level</code>.
     */
    public void setLevel(@Nullable Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_partition_tree.level</code>.
     */
    @Nullable
    public Integer getLevel() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row4<Object, Object, Boolean, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row4<Object, Object, Boolean, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Override
    @NotNull
    public Field<Object> field1() {
        return PgPartitionTree.PG_PARTITION_TREE.RELID;
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Override
    @NotNull
    public Field<Object> field2() {
        return PgPartitionTree.PG_PARTITION_TREE.PARENTRELID;
    }

    @Override
    @NotNull
    public Field<Boolean> field3() {
        return PgPartitionTree.PG_PARTITION_TREE.ISLEAF;
    }

    @Override
    @NotNull
    public Field<Integer> field4() {
        return PgPartitionTree.PG_PARTITION_TREE.LEVEL;
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Override
    @Nullable
    public Object component1() {
        return getRelid();
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Override
    @Nullable
    public Object component2() {
        return getParentrelid();
    }

    @Override
    @Nullable
    public Boolean component3() {
        return getIsleaf();
    }

    @Override
    @Nullable
    public Integer component4() {
        return getLevel();
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Override
    @Nullable
    public Object value1() {
        return getRelid();
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Override
    @Nullable
    public Object value2() {
        return getParentrelid();
    }

    @Override
    @Nullable
    public Boolean value3() {
        return getIsleaf();
    }

    @Override
    @Nullable
    public Integer value4() {
        return getLevel();
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Override
    @NotNull
    public PgPartitionTreeRecord value1(@Nullable Object value) {
        setRelid(value);
        return this;
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Override
    @NotNull
    public PgPartitionTreeRecord value2(@Nullable Object value) {
        setParentrelid(value);
        return this;
    }

    @Override
    @NotNull
    public PgPartitionTreeRecord value3(@Nullable Boolean value) {
        setIsleaf(value);
        return this;
    }

    @Override
    @NotNull
    public PgPartitionTreeRecord value4(@Nullable Integer value) {
        setLevel(value);
        return this;
    }

    @Override
    @NotNull
    public PgPartitionTreeRecord values(@Nullable Object value1, @Nullable Object value2, @Nullable Boolean value3, @Nullable Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PgPartitionTreeRecord
     */
    public PgPartitionTreeRecord() {
        super(PgPartitionTree.PG_PARTITION_TREE);
    }

    /**
     * Create a detached, initialised PgPartitionTreeRecord
     */
    @ConstructorProperties({ "relid", "parentrelid", "isleaf", "level" })
    public PgPartitionTreeRecord(@Nullable Object relid, @Nullable Object parentrelid, @Nullable Boolean isleaf, @Nullable Integer level) {
        super(PgPartitionTree.PG_PARTITION_TREE);

        setRelid(relid);
        setParentrelid(parentrelid);
        setIsleaf(isleaf);
        setLevel(level);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised PgPartitionTreeRecord
     */
    public PgPartitionTreeRecord(edu.java.domain.jooq.pg_catalog.tables.pojos.PgPartitionTree value) {
        super(PgPartitionTree.PG_PARTITION_TREE);

        if (value != null) {
            setRelid(value.getRelid());
            setParentrelid(value.getParentrelid());
            setIsleaf(value.getIsleaf());
            setLevel(value.getLevel());
            resetChangedOnNotNull();
        }
    }
}
