/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.pg_catalog.tables.records;


import edu.java.domain.jooq.pg_catalog.tables.PgPublicationTables;

import java.beans.ConstructorProperties;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


/**
 * The table <code>pg_catalog.pg_publication_tables</code>.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PgPublicationTablesRecord extends TableRecordImpl<PgPublicationTablesRecord> implements Record5<String, String, String, String[], String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>pg_catalog.pg_publication_tables.pubname</code>.
     */
    public void setPubname(@Nullable String value) {
        set(0, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_publication_tables.pubname</code>.
     */
    @Nullable
    public String getPubname() {
        return (String) get(0);
    }

    /**
     * Setter for <code>pg_catalog.pg_publication_tables.schemaname</code>.
     */
    public void setSchemaname(@Nullable String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_publication_tables.schemaname</code>.
     */
    @Nullable
    public String getSchemaname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>pg_catalog.pg_publication_tables.tablename</code>.
     */
    public void setTablename(@Nullable String value) {
        set(2, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_publication_tables.tablename</code>.
     */
    @Nullable
    public String getTablename() {
        return (String) get(2);
    }

    /**
     * Setter for <code>pg_catalog.pg_publication_tables.attnames</code>.
     */
    public void setAttnames(@Nullable String[] value) {
        set(3, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_publication_tables.attnames</code>.
     */
    @Nullable
    public String[] getAttnames() {
        return (String[]) get(3);
    }

    /**
     * Setter for <code>pg_catalog.pg_publication_tables.rowfilter</code>.
     */
    public void setRowfilter(@Nullable String value) {
        set(4, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_publication_tables.rowfilter</code>.
     */
    @Nullable
    public String getRowfilter() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row5<String, String, String, String[], String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row5<String, String, String, String[], String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<String> field1() {
        return PgPublicationTables.PG_PUBLICATION_TABLES.PUBNAME;
    }

    @Override
    @NotNull
    public Field<String> field2() {
        return PgPublicationTables.PG_PUBLICATION_TABLES.SCHEMANAME;
    }

    @Override
    @NotNull
    public Field<String> field3() {
        return PgPublicationTables.PG_PUBLICATION_TABLES.TABLENAME;
    }

    @Override
    @NotNull
    public Field<String[]> field4() {
        return PgPublicationTables.PG_PUBLICATION_TABLES.ATTNAMES;
    }

    @Override
    @NotNull
    public Field<String> field5() {
        return PgPublicationTables.PG_PUBLICATION_TABLES.ROWFILTER;
    }

    @Override
    @Nullable
    public String component1() {
        return getPubname();
    }

    @Override
    @Nullable
    public String component2() {
        return getSchemaname();
    }

    @Override
    @Nullable
    public String component3() {
        return getTablename();
    }

    @Override
    @Nullable
    public String[] component4() {
        return getAttnames();
    }

    @Override
    @Nullable
    public String component5() {
        return getRowfilter();
    }

    @Override
    @Nullable
    public String value1() {
        return getPubname();
    }

    @Override
    @Nullable
    public String value2() {
        return getSchemaname();
    }

    @Override
    @Nullable
    public String value3() {
        return getTablename();
    }

    @Override
    @Nullable
    public String[] value4() {
        return getAttnames();
    }

    @Override
    @Nullable
    public String value5() {
        return getRowfilter();
    }

    @Override
    @NotNull
    public PgPublicationTablesRecord value1(@Nullable String value) {
        setPubname(value);
        return this;
    }

    @Override
    @NotNull
    public PgPublicationTablesRecord value2(@Nullable String value) {
        setSchemaname(value);
        return this;
    }

    @Override
    @NotNull
    public PgPublicationTablesRecord value3(@Nullable String value) {
        setTablename(value);
        return this;
    }

    @Override
    @NotNull
    public PgPublicationTablesRecord value4(@Nullable String[] value) {
        setAttnames(value);
        return this;
    }

    @Override
    @NotNull
    public PgPublicationTablesRecord value5(@Nullable String value) {
        setRowfilter(value);
        return this;
    }

    @Override
    @NotNull
    public PgPublicationTablesRecord values(@Nullable String value1, @Nullable String value2, @Nullable String value3, @Nullable String[] value4, @Nullable String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PgPublicationTablesRecord
     */
    public PgPublicationTablesRecord() {
        super(PgPublicationTables.PG_PUBLICATION_TABLES);
    }

    /**
     * Create a detached, initialised PgPublicationTablesRecord
     */
    @ConstructorProperties({ "pubname", "schemaname", "tablename", "attnames", "rowfilter" })
    public PgPublicationTablesRecord(@Nullable String pubname, @Nullable String schemaname, @Nullable String tablename, @Nullable String[] attnames, @Nullable String rowfilter) {
        super(PgPublicationTables.PG_PUBLICATION_TABLES);

        setPubname(pubname);
        setSchemaname(schemaname);
        setTablename(tablename);
        setAttnames(attnames);
        setRowfilter(rowfilter);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised PgPublicationTablesRecord
     */
    public PgPublicationTablesRecord(edu.java.domain.jooq.pg_catalog.tables.pojos.PgPublicationTables value) {
        super(PgPublicationTables.PG_PUBLICATION_TABLES);

        if (value != null) {
            setPubname(value.getPubname());
            setSchemaname(value.getSchemaname());
            setTablename(value.getTablename());
            setAttnames(value.getAttnames());
            setRowfilter(value.getRowfilter());
            resetChangedOnNotNull();
        }
    }
}
