/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.pg_catalog.tables.records;


import edu.java.domain.jooq.pg_catalog.tables.PgReplicationSlots;

import java.beans.ConstructorProperties;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.TableRecordImpl;


@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PgReplicationSlotsRecord extends TableRecordImpl<PgReplicationSlotsRecord> implements Record16<String, String, String, Long, String, Boolean, Boolean, Integer, Long, Long, Object, Object, String, Long, Boolean, Boolean> {

    private static final long serialVersionUID = 1L;

    public void setSlotName(@Nullable String value) {
        set(0, value);
    }

    @Nullable
    public String getSlotName() {
        return (String) get(0);
    }

    public void setPlugin(@Nullable String value) {
        set(1, value);
    }

    @Nullable
    public String getPlugin() {
        return (String) get(1);
    }

    public void setSlotType(@Nullable String value) {
        set(2, value);
    }

    @Nullable
    public String getSlotType() {
        return (String) get(2);
    }

    public void setDatoid(@Nullable Long value) {
        set(3, value);
    }

    @Nullable
    public Long getDatoid() {
        return (Long) get(3);
    }

    public void setDatabase(@Nullable String value) {
        set(4, value);
    }

    @Nullable
    public String getDatabase() {
        return (String) get(4);
    }

    public void setTemporary(@Nullable Boolean value) {
        set(5, value);
    }

    @Nullable
    public Boolean getTemporary() {
        return (Boolean) get(5);
    }

    public void setActive(@Nullable Boolean value) {
        set(6, value);
    }

    @Nullable
    public Boolean getActive() {
        return (Boolean) get(6);
    }

    public void setActivePid(@Nullable Integer value) {
        set(7, value);
    }

    @Nullable
    public Integer getActivePid() {
        return (Integer) get(7);
    }

    public void setXmin(@Nullable Long value) {
        set(8, value);
    }

    @Nullable
    public Long getXmin() {
        return (Long) get(8);
    }

    public void setCatalogXmin(@Nullable Long value) {
        set(9, value);
    }

    @Nullable
    public Long getCatalogXmin() {
        return (Long) get(9);
    }

    @Deprecated
    public void setRestartLsn(@Nullable Object value) {
        set(10, value);
    }

    @Deprecated
    @Nullable
    public Object getRestartLsn() {
        return get(10);
    }

    @Deprecated
    public void setConfirmedFlushLsn(@Nullable Object value) {
        set(11, value);
    }

    @Deprecated
    @Nullable
    public Object getConfirmedFlushLsn() {
        return get(11);
    }

    public void setWalStatus(@Nullable String value) {
        set(12, value);
    }

    @Nullable
    public String getWalStatus() {
        return (String) get(12);
    }

    public void setSafeWalSize(@Nullable Long value) {
        set(13, value);
    }

    @Nullable
    public Long getSafeWalSize() {
        return (Long) get(13);
    }

    public void setTwoPhase(@Nullable Boolean value) {
        set(14, value);
    }

    @Nullable
    public Boolean getTwoPhase() {
        return (Boolean) get(14);
    }

    public void setConflicting(@Nullable Boolean value) {
        set(15, value);
    }

    @Nullable
    public Boolean getConflicting() {
        return (Boolean) get(15);
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row16<String, String, String, Long, String, Boolean, Boolean, Integer, Long, Long, Object, Object, String, Long, Boolean, Boolean> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row16<String, String, String, Long, String, Boolean, Boolean, Integer, Long, Long, Object, Object, String, Long, Boolean, Boolean> valuesRow() {
        return (Row16) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<String> field1() {
        return PgReplicationSlots.PG_REPLICATION_SLOTS.SLOT_NAME;
    }

    @Override
    @NotNull
    public Field<String> field2() {
        return PgReplicationSlots.PG_REPLICATION_SLOTS.PLUGIN;
    }

    @Override
    @NotNull
    public Field<String> field3() {
        return PgReplicationSlots.PG_REPLICATION_SLOTS.SLOT_TYPE;
    }

    @Override
    @NotNull
    public Field<Long> field4() {
        return PgReplicationSlots.PG_REPLICATION_SLOTS.DATOID;
    }

    @Override
    @NotNull
    public Field<String> field5() {
        return PgReplicationSlots.PG_REPLICATION_SLOTS.DATABASE;
    }

    @Override
    @NotNull
    public Field<Boolean> field6() {
        return PgReplicationSlots.PG_REPLICATION_SLOTS.TEMPORARY;
    }

    @Override
    @NotNull
    public Field<Boolean> field7() {
        return PgReplicationSlots.PG_REPLICATION_SLOTS.ACTIVE;
    }

    @Override
    @NotNull
    public Field<Integer> field8() {
        return PgReplicationSlots.PG_REPLICATION_SLOTS.ACTIVE_PID;
    }

    @Override
    @NotNull
    public Field<Long> field9() {
        return PgReplicationSlots.PG_REPLICATION_SLOTS.XMIN;
    }

    @Override
    @NotNull
    public Field<Long> field10() {
        return PgReplicationSlots.PG_REPLICATION_SLOTS.CATALOG_XMIN;
    }

    @Deprecated
    @Override
    @NotNull
    public Field<Object> field11() {
        return PgReplicationSlots.PG_REPLICATION_SLOTS.RESTART_LSN;
    }

    @Deprecated
    @Override
    @NotNull
    public Field<Object> field12() {
        return PgReplicationSlots.PG_REPLICATION_SLOTS.CONFIRMED_FLUSH_LSN;
    }

    @Override
    @NotNull
    public Field<String> field13() {
        return PgReplicationSlots.PG_REPLICATION_SLOTS.WAL_STATUS;
    }

    @Override
    @NotNull
    public Field<Long> field14() {
        return PgReplicationSlots.PG_REPLICATION_SLOTS.SAFE_WAL_SIZE;
    }

    @Override
    @NotNull
    public Field<Boolean> field15() {
        return PgReplicationSlots.PG_REPLICATION_SLOTS.TWO_PHASE;
    }

    @Override
    @NotNull
    public Field<Boolean> field16() {
        return PgReplicationSlots.PG_REPLICATION_SLOTS.CONFLICTING;
    }

    @Override
    @Nullable
    public String component1() {
        return getSlotName();
    }

    @Override
    @Nullable
    public String component2() {
        return getPlugin();
    }

    @Override
    @Nullable
    public String component3() {
        return getSlotType();
    }

    @Override
    @Nullable
    public Long component4() {
        return getDatoid();
    }

    @Override
    @Nullable
    public String component5() {
        return getDatabase();
    }

    @Override
    @Nullable
    public Boolean component6() {
        return getTemporary();
    }

    @Override
    @Nullable
    public Boolean component7() {
        return getActive();
    }

    @Override
    @Nullable
    public Integer component8() {
        return getActivePid();
    }

    @Override
    @Nullable
    public Long component9() {
        return getXmin();
    }

    @Override
    @Nullable
    public Long component10() {
        return getCatalogXmin();
    }

    @Deprecated
    @Override
    @Nullable
    public Object component11() {
        return getRestartLsn();
    }

    @Deprecated
    @Override
    @Nullable
    public Object component12() {
        return getConfirmedFlushLsn();
    }

    @Override
    @Nullable
    public String component13() {
        return getWalStatus();
    }

    @Override
    @Nullable
    public Long component14() {
        return getSafeWalSize();
    }

    @Override
    @Nullable
    public Boolean component15() {
        return getTwoPhase();
    }

    @Override
    @Nullable
    public Boolean component16() {
        return getConflicting();
    }

    @Override
    @Nullable
    public String value1() {
        return getSlotName();
    }

    @Override
    @Nullable
    public String value2() {
        return getPlugin();
    }

    @Override
    @Nullable
    public String value3() {
        return getSlotType();
    }

    @Override
    @Nullable
    public Long value4() {
        return getDatoid();
    }

    @Override
    @Nullable
    public String value5() {
        return getDatabase();
    }

    @Override
    @Nullable
    public Boolean value6() {
        return getTemporary();
    }

    @Override
    @Nullable
    public Boolean value7() {
        return getActive();
    }

    @Override
    @Nullable
    public Integer value8() {
        return getActivePid();
    }

    @Override
    @Nullable
    public Long value9() {
        return getXmin();
    }

    @Override
    @Nullable
    public Long value10() {
        return getCatalogXmin();
    }

    @Deprecated
    @Override
    @Nullable
    public Object value11() {
        return getRestartLsn();
    }

    @Deprecated
    @Override
    @Nullable
    public Object value12() {
        return getConfirmedFlushLsn();
    }

    @Override
    @Nullable
    public String value13() {
        return getWalStatus();
    }

    @Override
    @Nullable
    public Long value14() {
        return getSafeWalSize();
    }

    @Override
    @Nullable
    public Boolean value15() {
        return getTwoPhase();
    }

    @Override
    @Nullable
    public Boolean value16() {
        return getConflicting();
    }

    @Override
    @NotNull
    public PgReplicationSlotsRecord value1(@Nullable String value) {
        setSlotName(value);
        return this;
    }

    @Override
    @NotNull
    public PgReplicationSlotsRecord value2(@Nullable String value) {
        setPlugin(value);
        return this;
    }

    @Override
    @NotNull
    public PgReplicationSlotsRecord value3(@Nullable String value) {
        setSlotType(value);
        return this;
    }

    @Override
    @NotNull
    public PgReplicationSlotsRecord value4(@Nullable Long value) {
        setDatoid(value);
        return this;
    }

    @Override
    @NotNull
    public PgReplicationSlotsRecord value5(@Nullable String value) {
        setDatabase(value);
        return this;
    }

    @Override
    @NotNull
    public PgReplicationSlotsRecord value6(@Nullable Boolean value) {
        setTemporary(value);
        return this;
    }

    @Override
    @NotNull
    public PgReplicationSlotsRecord value7(@Nullable Boolean value) {
        setActive(value);
        return this;
    }

    @Override
    @NotNull
    public PgReplicationSlotsRecord value8(@Nullable Integer value) {
        setActivePid(value);
        return this;
    }

    @Override
    @NotNull
    public PgReplicationSlotsRecord value9(@Nullable Long value) {
        setXmin(value);
        return this;
    }

    @Override
    @NotNull
    public PgReplicationSlotsRecord value10(@Nullable Long value) {
        setCatalogXmin(value);
        return this;
    }

    @Deprecated
    @Override
    @NotNull
    public PgReplicationSlotsRecord value11(@Nullable Object value) {
        setRestartLsn(value);
        return this;
    }

    @Deprecated
    @Override
    @NotNull
    public PgReplicationSlotsRecord value12(@Nullable Object value) {
        setConfirmedFlushLsn(value);
        return this;
    }

    @Override
    @NotNull
    public PgReplicationSlotsRecord value13(@Nullable String value) {
        setWalStatus(value);
        return this;
    }

    @Override
    @NotNull
    public PgReplicationSlotsRecord value14(@Nullable Long value) {
        setSafeWalSize(value);
        return this;
    }

    @Override
    @NotNull
    public PgReplicationSlotsRecord value15(@Nullable Boolean value) {
        setTwoPhase(value);
        return this;
    }

    @Override
    @NotNull
    public PgReplicationSlotsRecord value16(@Nullable Boolean value) {
        setConflicting(value);
        return this;
    }

    @Override
    @NotNull
    public PgReplicationSlotsRecord values(@Nullable String value1, @Nullable String value2, @Nullable String value3, @Nullable Long value4, @Nullable String value5, @Nullable Boolean value6, @Nullable Boolean value7, @Nullable Integer value8, @Nullable Long value9, @Nullable Long value10, @Nullable Object value11, @Nullable Object value12, @Nullable String value13, @Nullable Long value14, @Nullable Boolean value15, @Nullable Boolean value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    public PgReplicationSlotsRecord() {
        super(PgReplicationSlots.PG_REPLICATION_SLOTS);
    }

    @ConstructorProperties({ "slotName", "plugin", "slotType", "datoid", "database", "temporary", "active", "activePid", "xmin", "catalogXmin", "restartLsn", "confirmedFlushLsn", "walStatus", "safeWalSize", "twoPhase", "conflicting" })
    public PgReplicationSlotsRecord(@Nullable String slotName, @Nullable String plugin, @Nullable String slotType, @Nullable Long datoid, @Nullable String database, @Nullable Boolean temporary, @Nullable Boolean active, @Nullable Integer activePid, @Nullable Long xmin, @Nullable Long catalogXmin, @Nullable Object restartLsn, @Nullable Object confirmedFlushLsn, @Nullable String walStatus, @Nullable Long safeWalSize, @Nullable Boolean twoPhase, @Nullable Boolean conflicting) {
        super(PgReplicationSlots.PG_REPLICATION_SLOTS);

        setSlotName(slotName);
        setPlugin(plugin);
        setSlotType(slotType);
        setDatoid(datoid);
        setDatabase(database);
        setTemporary(temporary);
        setActive(active);
        setActivePid(activePid);
        setXmin(xmin);
        setCatalogXmin(catalogXmin);
        setRestartLsn(restartLsn);
        setConfirmedFlushLsn(confirmedFlushLsn);
        setWalStatus(walStatus);
        setSafeWalSize(safeWalSize);
        setTwoPhase(twoPhase);
        setConflicting(conflicting);
        resetChangedOnNotNull();
    }

    public PgReplicationSlotsRecord(edu.java.domain.jooq.pg_catalog.tables.pojos.PgReplicationSlots value) {
        super(PgReplicationSlots.PG_REPLICATION_SLOTS);

        if (value != null) {
            setSlotName(value.getSlotName());
            setPlugin(value.getPlugin());
            setSlotType(value.getSlotType());
            setDatoid(value.getDatoid());
            setDatabase(value.getDatabase());
            setTemporary(value.getTemporary());
            setActive(value.getActive());
            setActivePid(value.getActivePid());
            setXmin(value.getXmin());
            setCatalogXmin(value.getCatalogXmin());
            setRestartLsn(value.getRestartLsn());
            setConfirmedFlushLsn(value.getConfirmedFlushLsn());
            setWalStatus(value.getWalStatus());
            setSafeWalSize(value.getSafeWalSize());
            setTwoPhase(value.getTwoPhase());
            setConflicting(value.getConflicting());
            resetChangedOnNotNull();
        }
    }
}
