/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.pg_catalog.tables;


import edu.java.domain.jooq.pg_catalog.PgCatalog;
import edu.java.domain.jooq.pg_catalog.tables.records.JsonObjectKeysRecord;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.JSON;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JsonObjectKeys extends TableImpl<JsonObjectKeysRecord> {

    private static final long serialVersionUID = 1L;

    public static final JsonObjectKeys JSON_OBJECT_KEYS = new JsonObjectKeys();

    @Override
    @NotNull
    public Class<JsonObjectKeysRecord> getRecordType() {
        return JsonObjectKeysRecord.class;
    }

    public final TableField<JsonObjectKeysRecord, String> JSON_OBJECT_KEYS_ = createField(DSL.name("json_object_keys"), SQLDataType.CLOB, this, "");

    private JsonObjectKeys(Name alias, Table<JsonObjectKeysRecord> aliased) {
        this(alias, aliased, new Field[] {
            DSL.val(null, SQLDataType.JSON)
        });
    }

    private JsonObjectKeys(Name alias, Table<JsonObjectKeysRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.function());
    }

    public JsonObjectKeys(String alias) {
        this(DSL.name(alias), JSON_OBJECT_KEYS);
    }

    public JsonObjectKeys(Name alias) {
        this(alias, JSON_OBJECT_KEYS);
    }

    public JsonObjectKeys() {
        this(DSL.name("json_object_keys"), null);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : PgCatalog.PG_CATALOG;
    }

    @Override
    @NotNull
    public JsonObjectKeys as(String alias) {
        return new JsonObjectKeys(DSL.name(alias), this, parameters);
    }

    @Override
    @NotNull
    public JsonObjectKeys as(Name alias) {
        return new JsonObjectKeys(alias, this, parameters);
    }

    @Override
    @NotNull
    public JsonObjectKeys as(Table<?> alias) {
        return new JsonObjectKeys(alias.getQualifiedName(), this, parameters);
    }

    @Override
    @NotNull
    public JsonObjectKeys rename(String name) {
        return new JsonObjectKeys(DSL.name(name), null, parameters);
    }

    @Override
    @NotNull
    public JsonObjectKeys rename(Name name) {
        return new JsonObjectKeys(name, null, parameters);
    }

    @Override
    @NotNull
    public JsonObjectKeys rename(Table<?> name) {
        return new JsonObjectKeys(name.getQualifiedName(), null, parameters);
    }

    public JsonObjectKeys call(
          JSON __1
    ) {
        JsonObjectKeys result = new JsonObjectKeys(DSL.name("json_object_keys"), null, new Field[] {
            DSL.val(__1, SQLDataType.JSON)
        });

        return aliased() ? result.as(getUnqualifiedName()) : result;
    }

    public JsonObjectKeys call(
          Field<JSON> __1
    ) {
        JsonObjectKeys result = new JsonObjectKeys(DSL.name("json_object_keys"), null, new Field[] {
            __1
        });

        return aliased() ? result.as(getUnqualifiedName()) : result;
    }
}
