/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.pg_catalog.tables;


import edu.java.domain.jooq.pg_catalog.PgCatalog;
import edu.java.domain.jooq.pg_catalog.tables.records.PgAmRecord;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PgAm extends TableImpl<PgAmRecord> {

    private static final long serialVersionUID = 1L;

    public static final PgAm PG_AM = new PgAm();

    @Override
    @NotNull
    public Class<PgAmRecord> getRecordType() {
        return PgAmRecord.class;
    }

    public final TableField<PgAmRecord, Long> OID = createField(DSL.name("oid"), SQLDataType.BIGINT.nullable(false), this, "");

    public final TableField<PgAmRecord, String> AMNAME = createField(DSL.name("amname"), SQLDataType.VARCHAR.nullable(false), this, "");

    public final TableField<PgAmRecord, String> AMHANDLER = createField(DSL.name("amhandler"), SQLDataType.VARCHAR.nullable(false), this, "");

    public final TableField<PgAmRecord, String> AMTYPE = createField(DSL.name("amtype"), SQLDataType.CHAR.nullable(false), this, "");

    private PgAm(Name alias, Table<PgAmRecord> aliased) {
        this(alias, aliased, null);
    }

    private PgAm(Name alias, Table<PgAmRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public PgAm(String alias) {
        this(DSL.name(alias), PG_AM);
    }

    public PgAm(Name alias) {
        this(alias, PG_AM);
    }

    public PgAm() {
        this(DSL.name("pg_am"), null);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : PgCatalog.PG_CATALOG;
    }

    @Override
    @NotNull
    public PgAm as(String alias) {
        return new PgAm(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public PgAm as(Name alias) {
        return new PgAm(alias, this);
    }

    @Override
    @NotNull
    public PgAm as(Table<?> alias) {
        return new PgAm(alias.getQualifiedName(), this);
    }

    @Override
    @NotNull
    public PgAm rename(String name) {
        return new PgAm(DSL.name(name), null);
    }

    @Override
    @NotNull
    public PgAm rename(Name name) {
        return new PgAm(name, null);
    }

    @Override
    @NotNull
    public PgAm rename(Table<?> name) {
        return new PgAm(name.getQualifiedName(), null);
    }
}
