/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.pg_catalog.tables;


import edu.java.domain.jooq.pg_catalog.PgCatalog;
import edu.java.domain.jooq.pg_catalog.tables.records.PgInitPrivsRecord;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PgInitPrivs extends TableImpl<PgInitPrivsRecord> {

    private static final long serialVersionUID = 1L;

    public static final PgInitPrivs PG_INIT_PRIVS = new PgInitPrivs();

    @Override
    @NotNull
    public Class<PgInitPrivsRecord> getRecordType() {
        return PgInitPrivsRecord.class;
    }

    public final TableField<PgInitPrivsRecord, Long> OBJOID = createField(DSL.name("objoid"), SQLDataType.BIGINT.nullable(false), this, "");

    public final TableField<PgInitPrivsRecord, Long> CLASSOID = createField(DSL.name("classoid"), SQLDataType.BIGINT.nullable(false), this, "");

    public final TableField<PgInitPrivsRecord, Integer> OBJSUBID = createField(DSL.name("objsubid"), SQLDataType.INTEGER.nullable(false), this, "");

    public final TableField<PgInitPrivsRecord, String> PRIVTYPE = createField(DSL.name("privtype"), SQLDataType.CHAR.nullable(false), this, "");

    public final TableField<PgInitPrivsRecord, String[]> INITPRIVS = createField(DSL.name("initprivs"), SQLDataType.VARCHAR.nullable(false).array(), this, "");

    private PgInitPrivs(Name alias, Table<PgInitPrivsRecord> aliased) {
        this(alias, aliased, null);
    }

    private PgInitPrivs(Name alias, Table<PgInitPrivsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public PgInitPrivs(String alias) {
        this(DSL.name(alias), PG_INIT_PRIVS);
    }

    public PgInitPrivs(Name alias) {
        this(alias, PG_INIT_PRIVS);
    }

    public PgInitPrivs() {
        this(DSL.name("pg_init_privs"), null);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : PgCatalog.PG_CATALOG;
    }

    @Override
    @NotNull
    public PgInitPrivs as(String alias) {
        return new PgInitPrivs(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public PgInitPrivs as(Name alias) {
        return new PgInitPrivs(alias, this);
    }

    @Override
    @NotNull
    public PgInitPrivs as(Table<?> alias) {
        return new PgInitPrivs(alias.getQualifiedName(), this);
    }

    @Override
    @NotNull
    public PgInitPrivs rename(String name) {
        return new PgInitPrivs(DSL.name(name), null);
    }

    @Override
    @NotNull
    public PgInitPrivs rename(Name name) {
        return new PgInitPrivs(name, null);
    }

    @Override
    @NotNull
    public PgInitPrivs rename(Table<?> name) {
        return new PgInitPrivs(name.getQualifiedName(), null);
    }
}
