/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.pg_catalog.tables;


import edu.java.domain.jooq.pg_catalog.PgCatalog;
import edu.java.domain.jooq.pg_catalog.tables.records.PgLsReplslotdirRecord;

import java.time.OffsetDateTime;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PgLsReplslotdir extends TableImpl<PgLsReplslotdirRecord> {

    private static final long serialVersionUID = 1L;

    public static final PgLsReplslotdir PG_LS_REPLSLOTDIR = new PgLsReplslotdir();

    @Override
    @NotNull
    public Class<PgLsReplslotdirRecord> getRecordType() {
        return PgLsReplslotdirRecord.class;
    }

    public final TableField<PgLsReplslotdirRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB, this, "");

    public final TableField<PgLsReplslotdirRecord, Long> SIZE = createField(DSL.name("size"), SQLDataType.BIGINT, this, "");

    public final TableField<PgLsReplslotdirRecord, OffsetDateTime> MODIFICATION = createField(DSL.name("modification"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    private PgLsReplslotdir(Name alias, Table<PgLsReplslotdirRecord> aliased) {
        this(alias, aliased, new Field[] {
            DSL.val(null, SQLDataType.CLOB)
        });
    }

    private PgLsReplslotdir(Name alias, Table<PgLsReplslotdirRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.function());
    }

    public PgLsReplslotdir(String alias) {
        this(DSL.name(alias), PG_LS_REPLSLOTDIR);
    }

    public PgLsReplslotdir(Name alias) {
        this(alias, PG_LS_REPLSLOTDIR);
    }

    public PgLsReplslotdir() {
        this(DSL.name("pg_ls_replslotdir"), null);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : PgCatalog.PG_CATALOG;
    }

    @Override
    @NotNull
    public PgLsReplslotdir as(String alias) {
        return new PgLsReplslotdir(DSL.name(alias), this, parameters);
    }

    @Override
    @NotNull
    public PgLsReplslotdir as(Name alias) {
        return new PgLsReplslotdir(alias, this, parameters);
    }

    @Override
    @NotNull
    public PgLsReplslotdir as(Table<?> alias) {
        return new PgLsReplslotdir(alias.getQualifiedName(), this, parameters);
    }

    @Override
    @NotNull
    public PgLsReplslotdir rename(String name) {
        return new PgLsReplslotdir(DSL.name(name), null, parameters);
    }

    @Override
    @NotNull
    public PgLsReplslotdir rename(Name name) {
        return new PgLsReplslotdir(name, null, parameters);
    }

    @Override
    @NotNull
    public PgLsReplslotdir rename(Table<?> name) {
        return new PgLsReplslotdir(name.getQualifiedName(), null, parameters);
    }

    public PgLsReplslotdir call(
          String slotName
    ) {
        PgLsReplslotdir result = new PgLsReplslotdir(DSL.name("pg_ls_replslotdir"), null, new Field[] {
            DSL.val(slotName, SQLDataType.CLOB)
        });

        return aliased() ? result.as(getUnqualifiedName()) : result;
    }

    public PgLsReplslotdir call(
          Field<String> slotName
    ) {
        PgLsReplslotdir result = new PgLsReplslotdir(DSL.name("pg_ls_replslotdir"), null, new Field[] {
            slotName
        });

        return aliased() ? result.as(getUnqualifiedName()) : result;
    }
}
