/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.pg_catalog.tables;


import edu.java.domain.jooq.pg_catalog.PgCatalog;
import edu.java.domain.jooq.pg_catalog.tables.records.PgParameterAclRecord;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PgParameterAcl extends TableImpl<PgParameterAclRecord> {

    private static final long serialVersionUID = 1L;

    public static final PgParameterAcl PG_PARAMETER_ACL = new PgParameterAcl();

    @Override
    @NotNull
    public Class<PgParameterAclRecord> getRecordType() {
        return PgParameterAclRecord.class;
    }

    public final TableField<PgParameterAclRecord, Long> OID = createField(DSL.name("oid"), SQLDataType.BIGINT.nullable(false), this, "");

    public final TableField<PgParameterAclRecord, String> PARNAME = createField(DSL.name("parname"), SQLDataType.CLOB.nullable(false), this, "");

    public final TableField<PgParameterAclRecord, String[]> PARACL = createField(DSL.name("paracl"), SQLDataType.VARCHAR.array(), this, "");

    private PgParameterAcl(Name alias, Table<PgParameterAclRecord> aliased) {
        this(alias, aliased, null);
    }

    private PgParameterAcl(Name alias, Table<PgParameterAclRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public PgParameterAcl(String alias) {
        this(DSL.name(alias), PG_PARAMETER_ACL);
    }

    public PgParameterAcl(Name alias) {
        this(alias, PG_PARAMETER_ACL);
    }

    public PgParameterAcl() {
        this(DSL.name("pg_parameter_acl"), null);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : PgCatalog.PG_CATALOG;
    }

    @Override
    @NotNull
    public PgParameterAcl as(String alias) {
        return new PgParameterAcl(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public PgParameterAcl as(Name alias) {
        return new PgParameterAcl(alias, this);
    }

    @Override
    @NotNull
    public PgParameterAcl as(Table<?> alias) {
        return new PgParameterAcl(alias.getQualifiedName(), this);
    }

    @Override
    @NotNull
    public PgParameterAcl rename(String name) {
        return new PgParameterAcl(DSL.name(name), null);
    }

    @Override
    @NotNull
    public PgParameterAcl rename(Name name) {
        return new PgParameterAcl(name, null);
    }

    @Override
    @NotNull
    public PgParameterAcl rename(Table<?> name) {
        return new PgParameterAcl(name.getQualifiedName(), null);
    }
}
