/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.pg_catalog.tables;


import edu.java.domain.jooq.pg_catalog.PgCatalog;
import edu.java.domain.jooq.pg_catalog.tables.records.PgStatioUserTablesRecord;

import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function11;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row11;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PgStatioUserTables extends TableImpl<PgStatioUserTablesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>pg_catalog.pg_statio_user_tables</code>
     */
    public static final PgStatioUserTables PG_STATIO_USER_TABLES = new PgStatioUserTables();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<PgStatioUserTablesRecord> getRecordType() {
        return PgStatioUserTablesRecord.class;
    }

    /**
     * The column <code>pg_catalog.pg_statio_user_tables.relid</code>.
     */
    public final TableField<PgStatioUserTablesRecord, Long> RELID = createField(DSL.name("relid"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>pg_catalog.pg_statio_user_tables.schemaname</code>.
     */
    public final TableField<PgStatioUserTablesRecord, String> SCHEMANAME = createField(DSL.name("schemaname"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>pg_catalog.pg_statio_user_tables.relname</code>.
     */
    public final TableField<PgStatioUserTablesRecord, String> RELNAME = createField(DSL.name("relname"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>pg_catalog.pg_statio_user_tables.heap_blks_read</code>.
     */
    public final TableField<PgStatioUserTablesRecord, Long> HEAP_BLKS_READ = createField(DSL.name("heap_blks_read"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>pg_catalog.pg_statio_user_tables.heap_blks_hit</code>.
     */
    public final TableField<PgStatioUserTablesRecord, Long> HEAP_BLKS_HIT = createField(DSL.name("heap_blks_hit"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>pg_catalog.pg_statio_user_tables.idx_blks_read</code>.
     */
    public final TableField<PgStatioUserTablesRecord, Long> IDX_BLKS_READ = createField(DSL.name("idx_blks_read"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>pg_catalog.pg_statio_user_tables.idx_blks_hit</code>.
     */
    public final TableField<PgStatioUserTablesRecord, Long> IDX_BLKS_HIT = createField(DSL.name("idx_blks_hit"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>pg_catalog.pg_statio_user_tables.toast_blks_read</code>.
     */
    public final TableField<PgStatioUserTablesRecord, Long> TOAST_BLKS_READ = createField(DSL.name("toast_blks_read"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>pg_catalog.pg_statio_user_tables.toast_blks_hit</code>.
     */
    public final TableField<PgStatioUserTablesRecord, Long> TOAST_BLKS_HIT = createField(DSL.name("toast_blks_hit"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>pg_catalog.pg_statio_user_tables.tidx_blks_read</code>.
     */
    public final TableField<PgStatioUserTablesRecord, Long> TIDX_BLKS_READ = createField(DSL.name("tidx_blks_read"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>pg_catalog.pg_statio_user_tables.tidx_blks_hit</code>.
     */
    public final TableField<PgStatioUserTablesRecord, Long> TIDX_BLKS_HIT = createField(DSL.name("tidx_blks_hit"), SQLDataType.BIGINT, this, "");

    private PgStatioUserTables(Name alias, Table<PgStatioUserTablesRecord> aliased) {
        this(alias, aliased, null);
    }

    private PgStatioUserTables(Name alias, Table<PgStatioUserTablesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view("""
        create view "pg_statio_user_tables" as  SELECT relid,
          schemaname,
          relname,
          heap_blks_read,
          heap_blks_hit,
          idx_blks_read,
          idx_blks_hit,
          toast_blks_read,
          toast_blks_hit,
          tidx_blks_read,
          tidx_blks_hit
         FROM pg_statio_all_tables
        WHERE ((schemaname <> ALL (ARRAY['pg_catalog'::name, 'information_schema'::name])) AND (schemaname !~ '^pg_toast'::text));
        """));
    }

    /**
     * Create an aliased <code>pg_catalog.pg_statio_user_tables</code> table
     * reference
     */
    public PgStatioUserTables(String alias) {
        this(DSL.name(alias), PG_STATIO_USER_TABLES);
    }

    /**
     * Create an aliased <code>pg_catalog.pg_statio_user_tables</code> table
     * reference
     */
    public PgStatioUserTables(Name alias) {
        this(alias, PG_STATIO_USER_TABLES);
    }

    /**
     * Create a <code>pg_catalog.pg_statio_user_tables</code> table reference
     */
    public PgStatioUserTables() {
        this(DSL.name("pg_statio_user_tables"), null);
    }

    public <O extends Record> PgStatioUserTables(Table<O> child, ForeignKey<O, PgStatioUserTablesRecord> key) {
        super(child, key, PG_STATIO_USER_TABLES);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : PgCatalog.PG_CATALOG;
    }

    @Override
    @NotNull
    public PgStatioUserTables as(String alias) {
        return new PgStatioUserTables(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public PgStatioUserTables as(Name alias) {
        return new PgStatioUserTables(alias, this);
    }

    @Override
    @NotNull
    public PgStatioUserTables as(Table<?> alias) {
        return new PgStatioUserTables(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public PgStatioUserTables rename(String name) {
        return new PgStatioUserTables(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public PgStatioUserTables rename(Name name) {
        return new PgStatioUserTables(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public PgStatioUserTables rename(Table<?> name) {
        return new PgStatioUserTables(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row11 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row11<Long, String, String, Long, Long, Long, Long, Long, Long, Long, Long> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function11<? super Long, ? super String, ? super String, ? super Long, ? super Long, ? super Long, ? super Long, ? super Long, ? super Long, ? super Long, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function11<? super Long, ? super String, ? super String, ? super Long, ? super Long, ? super Long, ? super Long, ? super Long, ? super Long, ? super Long, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
